begin;

create table if not exists field_catalog
(
    id bigint generated by default as identity,
    field_key character varying(150) not null,
    normalized_field_key character varying(150) not null,
    resource_key character varying(100) not null,
    normalized_resource_key character varying(100) not null,
    property_name character varying(100) not null,
    normalized_property_name character varying(100) not null,
    display_name character varying(120) not null,
    is_configurable boolean not null,
    is_sensitive boolean not null,
    data_type character varying(40) not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_field_catalog primary key (id)
);

create table if not exists role_field_permissions
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_id bigint not null,
    field_key character varying(150) not null,
    normalized_field_key character varying(150) not null,
    is_visible boolean not null,
    is_editable boolean not null,
    is_required boolean not null,
    is_masked boolean not null,
    updated_by_user_id uuid not null,
    updated_at_utc timestamp with time zone not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_role_field_permissions primary key (id),
    constraint fk_role_field_permissions__iam_roles__role_id
        foreign key (role_id) references iam_roles (id) on delete cascade
);

create table if not exists field_permission_audit_logs
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_public_id uuid not null,
    field_key character varying(150) not null,
    normalized_field_key character varying(150) not null,
    changed_by_user_id uuid not null,
    before_json jsonb,
    after_json jsonb not null,
    changed_at_utc timestamp with time zone not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_field_permission_audit_logs primary key (id)
);

create unique index if not exists uq_field_catalog__normalized_field_key
    on field_catalog (normalized_field_key);

create index if not exists ix_field_catalog__resource_configurable
    on field_catalog (normalized_resource_key, is_configurable);

create unique index if not exists uq_role_field_permissions__tenant_role_field
    on role_field_permissions (tenant_id, role_id, normalized_field_key);

create index if not exists ix_role_field_permissions__tenant_role
    on role_field_permissions (tenant_id, role_id);

create index if not exists ix_field_permission_audit_logs__tenant_role_changed_at
    on field_permission_audit_logs (tenant_id, role_public_id, changed_at_utc);

create index if not exists ix_field_permission_audit_logs__tenant_field_changed_at
    on field_permission_audit_logs (tenant_id, normalized_field_key, changed_at_utc);

insert into field_catalog (
    field_key,
    normalized_field_key,
    resource_key,
    normalized_resource_key,
    property_name,
    normalized_property_name,
    display_name,
    is_configurable,
    is_sensitive,
    data_type,
    created_utc,
    modified_utc)
values
    ('RBAC_USERS.ID', 'RBAC_USERS.ID', 'RBAC_USERS', 'RBAC_USERS', 'Id', 'ID', 'Internal Id', false, false, 'guid', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.EMAIL', 'RBAC_USERS.EMAIL', 'RBAC_USERS', 'RBAC_USERS', 'Email', 'EMAIL', 'Email', true, true, 'string', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.FIRST_NAME', 'RBAC_USERS.FIRST_NAME', 'RBAC_USERS', 'RBAC_USERS', 'FirstName', 'FIRSTNAME', 'First Name', true, false, 'string', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.LAST_NAME', 'RBAC_USERS.LAST_NAME', 'RBAC_USERS', 'RBAC_USERS', 'LastName', 'LASTNAME', 'Last Name', true, false, 'string', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.ROLE', 'RBAC_USERS.ROLE', 'RBAC_USERS', 'RBAC_USERS', 'Role', 'ROLE', 'Role', true, false, 'lookup', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.STATUS', 'RBAC_USERS.STATUS', 'RBAC_USERS', 'RBAC_USERS', 'Status', 'STATUS', 'Status', true, false, 'enum', now() at time zone 'utc', now() at time zone 'utc')
on conflict (normalized_field_key) do update
set resource_key = excluded.resource_key,
    normalized_resource_key = excluded.normalized_resource_key,
    property_name = excluded.property_name,
    normalized_property_name = excluded.normalized_property_name,
    display_name = excluded.display_name,
    is_configurable = excluded.is_configurable,
    is_sensitive = excluded.is_sensitive,
    data_type = excluded.data_type,
    modified_utc = excluded.modified_utc;

commit;
