begin;

create table if not exists companies
(
    id bigint generated by default as identity,
    public_id uuid not null,
    name character varying(150) not null,
    slug character varying(120) not null,
    status character varying(30) not null,
    created_by_user_public_id uuid not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_companies primary key (id)
);

create unique index if not exists uq_companies__public_id
    on companies (public_id);

create unique index if not exists uq_companies__slug
    on companies (slug);

create table if not exists company_subscriptions
(
    id bigint generated by default as identity,
    company_id bigint not null,
    plan_code character varying(40) not null,
    status character varying(30) not null,
    start_date_utc timestamp with time zone not null,
    end_date_utc timestamp with time zone,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_company_subscriptions primary key (id),
    constraint fk_company_subscriptions__companies
        foreign key (company_id) references companies (id) on delete cascade
);

create unique index if not exists uq_company_subscriptions__company_active
    on company_subscriptions (company_id, status)
    where status = 'Active';

create table if not exists plan_entitlements
(
    id bigint generated by default as identity,
    plan_code character varying(40) not null,
    module_key character varying(60) not null,
    is_enabled boolean not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_plan_entitlements primary key (id)
);

create unique index if not exists uq_plan_entitlements__plan_module
    on plan_entitlements (plan_code, module_key);

alter table iam_roles
    add column if not exists is_system_role boolean not null default false;

create table if not exists user_companies
(
    id bigint generated by default as identity,
    user_id bigint not null,
    company_id bigint not null,
    role_id bigint not null,
    is_primary boolean not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_user_companies primary key (id),
    constraint fk_user_companies__auth_users
        foreign key (user_id) references auth_users (id) on delete cascade,
    constraint fk_user_companies__companies
        foreign key (company_id) references companies (id) on delete cascade,
    constraint fk_user_companies__iam_roles
        foreign key (role_id) references iam_roles (id) on delete restrict
);

create unique index if not exists uq_user_companies__primary_user
    on user_companies (user_id)
    where is_primary = true;

create unique index if not exists uq_user_companies__user_company
    on user_companies (user_id, company_id);

insert into plan_entitlements (plan_code, module_key, is_enabled, created_utc, modified_utc)
select 'FREE', 'RBAC', true, now() at time zone 'utc', now() at time zone 'utc'
where not exists (
    select 1
    from plan_entitlements
    where plan_code = 'FREE'
      and module_key = 'RBAC'
);

insert into plan_entitlements (plan_code, module_key, is_enabled, created_utc, modified_utc)
select 'FREE', 'USERS', true, now() at time zone 'utc', now() at time zone 'utc'
where not exists (
    select 1
    from plan_entitlements
    where plan_code = 'FREE'
      and module_key = 'USERS'
);

commit;
