begin;

alter table user_companies
    add column if not exists status character varying(30) not null default 'Active';

create index if not exists ix_user_companies__company_status_role
    on user_companies (company_id, status, role_id);

create table if not exists company_invitation_tokens
(
    id bigint generated by default as identity,
    user_id bigint not null,
    company_id bigint not null,
    token_hash character varying(128) not null,
    expiration_utc timestamp with time zone not null,
    is_used boolean not null default false,
    revoked_utc timestamp with time zone,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_company_invitation_tokens primary key (id),
    constraint fk_company_invitation_tokens__auth_users
        foreign key (user_id) references auth_users (id) on delete cascade,
    constraint fk_company_invitation_tokens__companies
        foreign key (company_id) references companies (id) on delete cascade
);

create unique index if not exists uq_company_invitation_tokens__token_hash
    on company_invitation_tokens (token_hash);

create index if not exists ix_company_invitation_tokens__user_company
    on company_invitation_tokens (user_id, company_id);

commit;
