begin;

create table if not exists rbac_resource_catalog
(
    resource_key character varying(100) not null,
    normalized_resource_key character varying(100) not null,
    display_name character varying(120) not null,
    is_active boolean not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_rbac_resource_catalog primary key (resource_key)
);

create unique index if not exists uq_rbac_resource_catalog__normalized_resource_key
    on rbac_resource_catalog (normalized_resource_key);

create table if not exists rbac_permission_audit_logs
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_public_id uuid not null,
    resource_key character varying(100) not null,
    normalized_resource_key character varying(100) not null,
    changed_by_user_id uuid not null,
    change_type character varying(20) not null,
    before_json jsonb not null,
    after_json jsonb not null,
    changed_at_utc timestamp with time zone not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_rbac_permission_audit_logs primary key (id)
);

create index if not exists ix_rbac_permission_audit_logs__tenant_role_changed_at
    on rbac_permission_audit_logs (tenant_id, role_public_id, changed_at_utc);

create index if not exists ix_rbac_permission_audit_logs__tenant_resource_changed_at
    on rbac_permission_audit_logs (tenant_id, normalized_resource_key, changed_at_utc);

insert into rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc)
values
    ('RBAC_USERS', 'RBAC_USERS', 'Users', true, now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_ROLES', 'RBAC_ROLES', 'Roles', true, now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_PERMISSIONS', 'RBAC_PERMISSIONS', 'Permissions', true, now() at time zone 'utc', now() at time zone 'utc')
on conflict (resource_key) do update
set normalized_resource_key = excluded.normalized_resource_key,
    display_name = excluded.display_name,
    is_active = excluded.is_active,
    modified_utc = excluded.modified_utc;

commit;
