create table if not exists audit_logs
(
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    tenant_id uuid not null,
    actor_user_id uuid not null,
    actor_email varchar(320) null,
    event_type varchar(100) not null,
    entity_type varchar(50) not null,
    entity_id uuid null,
    entity_key varchar(150) null,
    action varchar(50) not null,
    summary varchar(500) not null,
    before_json jsonb null,
    after_json jsonb null,
    diff_json jsonb null,
    ip_address varchar(45) null,
    user_agent varchar(1000) null,
    created_utc timestamptz not null,
    modified_utc timestamptz null
);

create unique index if not exists ux_audit_logs__public_id
    on audit_logs (public_id);

create index if not exists ix_audit_logs__tenant_created
    on audit_logs (tenant_id, created_utc desc);

create index if not exists ix_audit_logs__tenant_actor_created
    on audit_logs (tenant_id, actor_user_id, created_utc desc);

create index if not exists ix_audit_logs__tenant_entity
    on audit_logs (tenant_id, entity_type, entity_id);

create index if not exists ix_audit_logs__tenant_event_created
    on audit_logs (tenant_id, event_type, created_utc desc);

insert into rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc)
values
    ('AUDIT_LOGS', 'AUDIT_LOGS', 'Audit Logs', true, now() at time zone 'utc', now() at time zone 'utc')
on conflict (resource_key) do update
set normalized_resource_key = excluded.normalized_resource_key,
    display_name = excluded.display_name,
    is_active = excluded.is_active,
    modified_utc = excluded.modified_utc;
