-- HU-016 - Legal representatives per company

CREATE TABLE IF NOT EXISTS legal_representatives (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    full_name character varying(201) NOT NULL,
    normalized_full_name character varying(201) NOT NULL,
    document_type character varying(40) NOT NULL,
    document_number character varying(80) NOT NULL,
    normalized_document_number character varying(80) NOT NULL,
    position_title character varying(150) NOT NULL,
    representation_type character varying(50) NOT NULL,
    authority_description character varying(500),
    appointment_instrument character varying(500),
    appointment_date_utc timestamp with time zone,
    effective_from_utc timestamp with time zone NOT NULL,
    effective_to_utc timestamp with time zone,
    email character varying(320),
    phone character varying(40),
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_legal_representatives PRIMARY KEY (id),
    CONSTRAINT ck_legal_representatives__effective_dates
        CHECK (effective_to_utc IS NULL OR effective_to_utc >= effective_from_utc)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_legal_representatives__public_id
    ON legal_representatives (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_legal_representatives__tenant_document_type_number
    ON legal_representatives (tenant_id, document_type, normalized_document_number);

CREATE UNIQUE INDEX IF NOT EXISTS ux_legal_representatives__tenant_primary_active
    ON legal_representatives (tenant_id, is_primary, is_active)
    WHERE is_primary = TRUE AND is_active = TRUE;

CREATE INDEX IF NOT EXISTS ix_legal_representatives__tenant_active
    ON legal_representatives (tenant_id, is_active);

CREATE INDEX IF NOT EXISTS ix_legal_representatives__tenant_primary
    ON legal_representatives (tenant_id, is_primary);

CREATE INDEX IF NOT EXISTS ix_legal_representatives__tenant_representation_active
    ON legal_representatives (tenant_id, representation_type, is_active);

CREATE INDEX IF NOT EXISTS ix_legal_representatives__tenant_normalized_name
    ON legal_representatives (tenant_id, normalized_full_name);

CREATE INDEX IF NOT EXISTS ix_legal_representatives__tenant_effective_dates
    ON legal_representatives (tenant_id, effective_from_utc, effective_to_utc);

WITH companies_without_representatives AS (
    SELECT
        companies.public_id AS tenant_id,
        companies.created_by_user_public_id AS owner_user_public_id,
        companies.created_utc AS company_created_utc
    FROM companies
    LEFT JOIN legal_representatives
        ON legal_representatives.tenant_id = companies.public_id
    WHERE legal_representatives.id IS NULL
),
seed_source AS (
    SELECT
        source.tenant_id,
        COALESCE(NULLIF(BTRIM(owner_user.first_name), ''), 'Representante') AS first_name,
        COALESCE(NULLIF(BTRIM(owner_user.last_name), ''), 'Migracion HU-0016') AS last_name,
        NULLIF(BTRIM(owner_user.email), '') AS email,
        COALESCE(source.company_created_utc, NOW()) AS company_created_utc
    FROM companies_without_representatives source
    LEFT JOIN auth_users owner_user
        ON owner_user.public_id = source.owner_user_public_id
)
INSERT INTO legal_representatives
(
    public_id,
    first_name,
    last_name,
    full_name,
    normalized_full_name,
    document_type,
    document_number,
    normalized_document_number,
    position_title,
    representation_type,
    authority_description,
    appointment_instrument,
    appointment_date_utc,
    effective_from_utc,
    effective_to_utc,
    email,
    phone,
    is_primary,
    is_active,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    (
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:public'), 1, 8) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:public'), 9, 4) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:public'), 13, 4) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:public'), 17, 4) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:public'), 21, 12)
    )::uuid,
    LEFT(seed.first_name, 100),
    LEFT(seed.last_name, 100),
    LEFT(CONCAT(LEFT(seed.first_name, 100), ' ', LEFT(seed.last_name, 100)), 201),
    UPPER(BTRIM(LEFT(CONCAT(LEFT(seed.first_name, 100), ' ', LEFT(seed.last_name, 100)), 201))),
    'Other',
    ('HU016-' || UPPER(SUBSTRING(MD5(seed.tenant_id::text), 1, 24))),
    ('HU016-' || UPPER(SUBSTRING(MD5(seed.tenant_id::text), 1, 24))),
    'Representante Legal',
    'PrimaryLegalRepresentative',
    'Backfilled by HU-0016 migration for companies without legal representatives.',
    'Backfilled by HU-0016 migration.',
    NULL,
    DATE_TRUNC('day', seed.company_created_utc),
    NULL,
    seed.email,
    NULL,
    TRUE,
    TRUE,
    (
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:token'), 1, 8) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:token'), 9, 4) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:token'), 13, 4) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:token'), 17, 4) || '-' ||
        SUBSTRING(MD5(seed.tenant_id::text || ':hu016:token'), 21, 12)
    )::uuid,
    NOW(),
    NOW(),
    seed.tenant_id
FROM seed_source seed
ON CONFLICT (tenant_id, document_type, normalized_document_number)
    DO NOTHING;
