-- HU-013 - Position slots and dependency graph

CREATE TABLE IF NOT EXISTS position_slots (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    title character varying(180),
    job_profile_id bigint NOT NULL,
    org_unit_id bigint NOT NULL,
    work_center_id bigint,
    cost_center_code character varying(100),
    direct_dependency_position_slot_id bigint,
    functional_dependency_position_slot_id bigint,
    status character varying(20) NOT NULL,
    max_employees integer NOT NULL,
    occupied_employees integer NOT NULL,
    is_fixed_term boolean NOT NULL,
    effective_from_utc timestamp with time zone NOT NULL,
    effective_to_utc timestamp with time zone,
    notes character varying(2000),
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_position_slots PRIMARY KEY (id),
    CONSTRAINT fk_position_slots__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_slots__org_unit FOREIGN KEY (org_unit_id) REFERENCES org_units (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_slots__work_center FOREIGN KEY (work_center_id) REFERENCES work_centers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_slots__direct_dependency FOREIGN KEY (direct_dependency_position_slot_id) REFERENCES position_slots (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_slots__functional_dependency FOREIGN KEY (functional_dependency_position_slot_id) REFERENCES position_slots (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_slots__public_id
    ON position_slots (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_slots__tenant_code
    ON position_slots (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_position_slots__tenant_status
    ON position_slots (tenant_id, status);

CREATE INDEX IF NOT EXISTS ix_position_slots__tenant_job_profile
    ON position_slots (tenant_id, job_profile_id);

CREATE INDEX IF NOT EXISTS ix_position_slots__tenant_org_unit
    ON position_slots (tenant_id, org_unit_id);

CREATE INDEX IF NOT EXISTS ix_position_slots__tenant_work_center
    ON position_slots (tenant_id, work_center_id);

CREATE INDEX IF NOT EXISTS ix_position_slots__tenant_direct_dependency
    ON position_slots (tenant_id, direct_dependency_position_slot_id);

CREATE INDEX IF NOT EXISTS ix_position_slots__tenant_functional_dependency
    ON position_slots (tenant_id, functional_dependency_position_slot_id);
