-- HU-012 - Job profiles and catalog administration

CREATE TABLE IF NOT EXISTS job_catalog_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    category character varying(50) NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(120) NOT NULL,
    normalized_name character varying(120) NOT NULL,
    is_system boolean NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_catalog_items PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_catalog_items__public_id
    ON job_catalog_items (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_catalog_items__tenant_category_code
    ON job_catalog_items (tenant_id, category, normalized_code);

CREATE INDEX IF NOT EXISTS ix_job_catalog_items__tenant_category_name
    ON job_catalog_items (tenant_id, category, normalized_name);

CREATE INDEX IF NOT EXISTS ix_job_catalog_items__tenant_category_active
    ON job_catalog_items (tenant_id, category, is_active);

CREATE TABLE IF NOT EXISTS job_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    title character varying(180) NOT NULL,
    normalized_title character varying(180) NOT NULL,
    objective character varying(4000),
    org_unit_id bigint,
    reports_to_job_profile_id bigint,
    decision_scope character varying(4000),
    assigned_resources character varying(4000),
    responsibilities character varying(4000),
    benefits_summary character varying(4000),
    working_condition_summary character varying(4000),
    market_salary_reference character varying(4000),
    valuation_notes character varying(4000),
    status character varying(20) NOT NULL,
    version integer NOT NULL,
    effective_from_utc timestamp with time zone,
    effective_to_utc timestamp with time zone,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profiles PRIMARY KEY (id),
    CONSTRAINT fk_job_profiles__org_unit FOREIGN KEY (org_unit_id) REFERENCES org_units (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_profiles__reports_to FOREIGN KEY (reports_to_job_profile_id) REFERENCES job_profiles (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_profiles__public_id
    ON job_profiles (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_profiles__tenant_code
    ON job_profiles (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_job_profiles__tenant_status
    ON job_profiles (tenant_id, status);

CREATE INDEX IF NOT EXISTS ix_job_profiles__tenant_org_unit
    ON job_profiles (tenant_id, org_unit_id);

CREATE INDEX IF NOT EXISTS ix_job_profiles__tenant_title
    ON job_profiles (tenant_id, normalized_title);

CREATE TABLE IF NOT EXISTS job_profile_requirements (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    requirement_type character varying(30) NOT NULL,
    catalog_item_id bigint,
    description character varying(1000) NOT NULL,
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_requirements PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_requirements__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_requirements__catalog_item FOREIGN KEY (catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_requirements__tenant_profile_sort
    ON job_profile_requirements (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_functions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    function_type character varying(20) NOT NULL,
    description character varying(2000) NOT NULL,
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_functions PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_functions__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_job_profile_functions__tenant_profile_sort
    ON job_profile_functions (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    relation_type character varying(20) NOT NULL,
    catalog_item_id bigint,
    counterpart character varying(500) NOT NULL,
    notes character varying(1000),
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_relations PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_relations__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_relations__catalog_item FOREIGN KEY (catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_relations__tenant_profile_sort
    ON job_profile_relations (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_competencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    catalog_item_id bigint,
    name character varying(300) NOT NULL,
    expected_level character varying(150),
    notes character varying(1000),
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_competencies PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_competencies__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_competencies__catalog_item FOREIGN KEY (catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_competencies__tenant_profile_sort
    ON job_profile_competencies (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_trainings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    catalog_item_id bigint,
    name character varying(300) NOT NULL,
    notes character varying(1000),
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_trainings PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_trainings__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_trainings__catalog_item FOREIGN KEY (catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_trainings__tenant_profile_sort
    ON job_profile_trainings (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_compensations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    salary_class_catalog_item_id bigint,
    salary_class_name character varying(120),
    min_salary numeric(18,2),
    max_salary numeric(18,2),
    currency_code character varying(10),
    work_schedule character varying(120),
    is_primary boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_compensations PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_compensations__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_compensations__salary_class FOREIGN KEY (salary_class_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_compensations__tenant_profile_primary
    ON job_profile_compensations (tenant_id, job_profile_id, is_primary);

CREATE TABLE IF NOT EXISTS job_profile_benefits (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    catalog_item_id bigint,
    name character varying(300) NOT NULL,
    notes character varying(1000),
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_benefits PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_benefits__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_benefits__catalog_item FOREIGN KEY (catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_benefits__tenant_profile_sort
    ON job_profile_benefits (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_working_conditions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    catalog_item_id bigint,
    name character varying(300) NOT NULL,
    notes character varying(1000),
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_working_conditions PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_working_conditions__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_working_conditions__catalog_item FOREIGN KEY (catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_working_conditions__tenant_profile_sort
    ON job_profile_working_conditions (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_dependent_positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_id bigint NOT NULL,
    dependent_job_profile_id bigint NOT NULL,
    quantity integer NOT NULL,
    notes character varying(1000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_dependent_positions PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_dependent_positions__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_dependent_positions__dependent_profile FOREIGN KEY (dependent_job_profile_id) REFERENCES job_profiles (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_job_profile_dependent_positions__tenant_profile_dep
    ON job_profile_dependent_positions (tenant_id, job_profile_id, dependent_job_profile_id);
