-- HU-019 - Organizational structure catalogs (company types, org unit types, functional areas)

CREATE TABLE IF NOT EXISTS company_type_catalog_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    owner_user_public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    description character varying(500),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    CONSTRAINT pk_company_type_catalog_items PRIMARY KEY (id),
    CONSTRAINT ck_company_type_catalog_items__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_company_type_catalog_items__public_id
    ON company_type_catalog_items (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_company_type_catalog_items__owner_code
    ON company_type_catalog_items (owner_user_public_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_company_type_catalog_items__owner_name
    ON company_type_catalog_items (owner_user_public_id, normalized_name);

CREATE INDEX IF NOT EXISTS ix_company_type_catalog_items__owner_active
    ON company_type_catalog_items (owner_user_public_id, is_active);

CREATE TABLE IF NOT EXISTS org_unit_type_catalog_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    description character varying(500),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    CONSTRAINT pk_org_unit_type_catalog_items PRIMARY KEY (id),
    CONSTRAINT ck_org_unit_type_catalog_items__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_unit_type_catalog_items__public_id
    ON org_unit_type_catalog_items (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_unit_type_catalog_items__tenant_code
    ON org_unit_type_catalog_items (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_org_unit_type_catalog_items__tenant_name
    ON org_unit_type_catalog_items (tenant_id, normalized_name);

CREATE INDEX IF NOT EXISTS ix_org_unit_type_catalog_items__tenant_active
    ON org_unit_type_catalog_items (tenant_id, is_active);

CREATE TABLE IF NOT EXISTS functional_area_catalog_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    description character varying(500),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    CONSTRAINT pk_functional_area_catalog_items PRIMARY KEY (id),
    CONSTRAINT ck_functional_area_catalog_items__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_functional_area_catalog_items__public_id
    ON functional_area_catalog_items (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_functional_area_catalog_items__tenant_code
    ON functional_area_catalog_items (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_functional_area_catalog_items__tenant_name
    ON functional_area_catalog_items (tenant_id, normalized_name);

CREATE INDEX IF NOT EXISTS ix_functional_area_catalog_items__tenant_active
    ON functional_area_catalog_items (tenant_id, is_active);

ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS company_type_catalog_item_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_companies__company_type_catalog_item')
    THEN
        ALTER TABLE companies
            ADD CONSTRAINT fk_companies__company_type_catalog_item
                FOREIGN KEY (company_type_catalog_item_id)
                REFERENCES company_type_catalog_items (id)
                ON DELETE RESTRICT;
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS ix_companies__company_type_catalog_item
    ON companies (company_type_catalog_item_id);

ALTER TABLE org_units
    ADD COLUMN IF NOT EXISTS org_unit_type_catalog_item_id bigint;

ALTER TABLE org_units
    ADD COLUMN IF NOT EXISTS functional_area_catalog_item_id bigint;

INSERT INTO org_unit_type_catalog_items (
    public_id,
    tenant_id,
    code,
    normalized_code,
    name,
    normalized_name,
    description,
    sort_order,
    is_active,
    concurrency_token,
    created_utc,
    modified_utc
)
SELECT
    gen_random_uuid(),
    source.tenant_id,
    source.code,
    source.normalized_code,
    source.name,
    source.normalized_name,
    NULL,
    source.sort_order,
    true,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
FROM (
    SELECT DISTINCT
        unit.tenant_id,
        btrim(unit.unit_type) AS code,
        upper(btrim(unit.unit_type)) AS normalized_code,
        btrim(unit.unit_type) AS name,
        upper(btrim(unit.unit_type)) AS normalized_name,
        CASE upper(btrim(unit.unit_type))
            WHEN 'DIRECCION' THEN 10
            WHEN 'GERENCIA' THEN 20
            WHEN 'DEPARTAMENTO' THEN 30
            WHEN 'COORDINACION' THEN 40
            WHEN 'UNIDAD' THEN 50
            WHEN 'OTRO' THEN 999
            ELSE 999
        END AS sort_order
    FROM org_units unit
    WHERE unit.unit_type IS NOT NULL
      AND btrim(unit.unit_type) <> ''
) AS source
WHERE NOT EXISTS (
    SELECT 1
    FROM org_unit_type_catalog_items existing
    WHERE existing.tenant_id = source.tenant_id
      AND existing.normalized_code = source.normalized_code
);

UPDATE org_units unit
SET org_unit_type_catalog_item_id = catalog.id
FROM org_unit_type_catalog_items catalog
WHERE unit.org_unit_type_catalog_item_id IS NULL
  AND catalog.tenant_id = unit.tenant_id
  AND catalog.normalized_code = upper(btrim(unit.unit_type));

UPDATE org_units unit
SET org_unit_type_catalog_item_id = fallback.id
FROM (
    SELECT tenant_id, MIN(id) AS id
    FROM org_unit_type_catalog_items
    GROUP BY tenant_id
) AS fallback
WHERE unit.org_unit_type_catalog_item_id IS NULL
  AND fallback.tenant_id = unit.tenant_id;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'org_units'
          AND column_name = 'unit_type')
    THEN
        ALTER TABLE org_units
            ALTER COLUMN org_unit_type_catalog_item_id SET NOT NULL;
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_org_units__org_unit_type_catalog_item')
    THEN
        ALTER TABLE org_units
            ADD CONSTRAINT fk_org_units__org_unit_type_catalog_item
                FOREIGN KEY (org_unit_type_catalog_item_id)
                REFERENCES org_unit_type_catalog_items (id)
                ON DELETE RESTRICT;
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_org_units__functional_area_catalog_item')
    THEN
        ALTER TABLE org_units
            ADD CONSTRAINT fk_org_units__functional_area_catalog_item
                FOREIGN KEY (functional_area_catalog_item_id)
                REFERENCES functional_area_catalog_items (id)
                ON DELETE RESTRICT;
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS ix_org_units__tenant_org_unit_type_catalog_item
    ON org_units (tenant_id, org_unit_type_catalog_item_id);

CREATE INDEX IF NOT EXISTS ix_org_units__tenant_functional_area_catalog_item
    ON org_units (tenant_id, functional_area_catalog_item_id);

ALTER TABLE org_units
    DROP COLUMN IF EXISTS unit_type;

INSERT INTO rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc
)
VALUES (
    'ORG_STRUCTURE_CATALOGS',
    'ORG_STRUCTURE_CATALOGS',
    'Org Structure Catalogs',
    true,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
)
ON CONFLICT (resource_key) DO UPDATE
SET normalized_resource_key = EXCLUDED.normalized_resource_key,
    display_name = EXCLUDED.display_name,
    is_active = EXCLUDED.is_active,
    modified_utc = EXCLUDED.modified_utc;

INSERT INTO plan_entitlements (
    plan_code,
    module_key,
    is_enabled,
    created_utc,
    modified_utc
)
VALUES (
    'FREE',
    'ORG_STRUCTURE_CATALOGS',
    true,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
)
ON CONFLICT (plan_code, module_key) DO UPDATE
SET is_enabled = EXCLUDED.is_enabled,
    modified_utc = EXCLUDED.modified_utc;

WITH tenants AS (
    SELECT DISTINCT tenant_id
    FROM iam_roles
),
permission_source AS (
    SELECT
        tenant_id,
        code,
        upper(code) AS normalized_code,
        name,
        description,
        module_name,
        upper(module_name) AS normalized_module,
        screen_name,
        upper(screen_name) AS normalized_screen,
        action_name,
        upper(action_name) AS normalized_action
    FROM tenants
    CROSS JOIN (
        VALUES
            ('OrgStructureCatalogs.Read', 'Read Org Structure Catalogs', 'Read organization structure catalogs.', 'ORG_STRUCTURE_CATALOGS', 'OrgStructureCatalogs', 'Read'),
            ('OrgStructureCatalogs.Admin', 'Admin Org Structure Catalogs', 'Manage organization structure catalogs.', 'ORG_STRUCTURE_CATALOGS', 'OrgStructureCatalogs', 'Manage')
    ) AS source(code, name, description, module_name, screen_name, action_name)
)
INSERT INTO iam_permissions (
    public_id,
    tenant_id,
    code,
    normalized_code,
    name,
    description,
    module,
    normalized_module,
    screen,
    normalized_screen,
    kind,
    action,
    normalized_action,
    field_name,
    normalized_field_name,
    field_access,
    created_utc,
    modified_utc
)
SELECT
    gen_random_uuid(),
    source.tenant_id,
    source.code,
    source.normalized_code,
    source.name,
    source.description,
    source.module_name,
    source.normalized_module,
    source.screen_name,
    source.normalized_screen,
    'ScreenAction',
    source.action_name,
    source.normalized_action,
    NULL,
    NULL,
    NULL,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
FROM permission_source source
ON CONFLICT (tenant_id, normalized_code) DO UPDATE
SET code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    module = EXCLUDED.module,
    normalized_module = EXCLUDED.normalized_module,
    screen = EXCLUDED.screen,
    normalized_screen = EXCLUDED.normalized_screen,
    kind = EXCLUDED.kind,
    action = EXCLUDED.action,
    normalized_action = EXCLUDED.normalized_action,
    modified_utc = EXCLUDED.modified_utc;

INSERT INTO iam_role_permission_assignments (
    role_id,
    permission_id,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    role.id,
    target_permission.id,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    role.tenant_id
FROM iam_roles role
JOIN iam_role_permission_assignments manage_assignment
    ON manage_assignment.role_id = role.id
   AND manage_assignment.tenant_id = role.tenant_id
JOIN iam_permissions manage_permission
    ON manage_permission.id = manage_assignment.permission_id
   AND manage_permission.tenant_id = role.tenant_id
JOIN iam_permissions target_permission
    ON target_permission.tenant_id = role.tenant_id
   AND target_permission.normalized_code IN ('ORGSTRUCTURECATALOGS.READ', 'ORGSTRUCTURECATALOGS.ADMIN')
WHERE manage_permission.normalized_code = 'IAM.ADMINISTRATION.MANAGE'
  AND NOT EXISTS (
      SELECT 1
      FROM iam_role_permission_assignments existing
      WHERE existing.role_id = role.id
        AND existing.permission_id = target_permission.id
  );
