-- HU-018 - Competency framework (occupational pyramid, conducts, matrix by job profile)

CREATE TABLE IF NOT EXISTS occupational_pyramid_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(120) NOT NULL,
    normalized_name character varying(120) NOT NULL,
    level_order integer NOT NULL,
    description character varying(500),
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_occupational_pyramid_levels PRIMARY KEY (id),
    CONSTRAINT ck_occupational_pyramid_levels__level_order CHECK (level_order > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_occupational_pyramid_levels__public_id
    ON occupational_pyramid_levels (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_occupational_pyramid_levels__tenant_code
    ON occupational_pyramid_levels (tenant_id, normalized_code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_occupational_pyramid_levels__tenant_level_order
    ON occupational_pyramid_levels (tenant_id, level_order);

CREATE INDEX IF NOT EXISTS ix_occupational_pyramid_levels__tenant_active
    ON occupational_pyramid_levels (tenant_id, is_active);

CREATE INDEX IF NOT EXISTS ix_occupational_pyramid_levels__tenant_name
    ON occupational_pyramid_levels (tenant_id, normalized_name);

CREATE TABLE IF NOT EXISTS competency_conducts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    competency_catalog_item_id bigint NOT NULL,
    competency_type_catalog_item_id bigint NOT NULL,
    behavior_level_catalog_item_id bigint NOT NULL,
    description character varying(1000) NOT NULL,
    normalized_description character varying(1000) NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_competency_conducts PRIMARY KEY (id),
    CONSTRAINT fk_competency_conducts__competency_catalog_item FOREIGN KEY (competency_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_competency_conducts__competency_type_catalog_item FOREIGN KEY (competency_type_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_competency_conducts__behavior_level_catalog_item FOREIGN KEY (behavior_level_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT ck_competency_conducts__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_competency_conducts__public_id
    ON competency_conducts (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_competency_conducts__tenant_competency_type_level_desc
    ON competency_conducts (
        tenant_id,
        competency_catalog_item_id,
        competency_type_catalog_item_id,
        behavior_level_catalog_item_id,
        normalized_description
    );

CREATE INDEX IF NOT EXISTS ix_competency_conducts__tenant_competency_type_level
    ON competency_conducts (tenant_id, competency_catalog_item_id, competency_type_catalog_item_id, behavior_level_catalog_item_id);

CREATE INDEX IF NOT EXISTS ix_competency_conducts__tenant_active
    ON competency_conducts (tenant_id, is_active);

CREATE TABLE IF NOT EXISTS competency_conduct_behaviors (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    competency_conduct_id bigint NOT NULL,
    behavior_catalog_item_id bigint NOT NULL,
    notes character varying(1000),
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_competency_conduct_behaviors PRIMARY KEY (id),
    CONSTRAINT fk_competency_conduct_behaviors__conduct FOREIGN KEY (competency_conduct_id) REFERENCES competency_conducts (id) ON DELETE CASCADE,
    CONSTRAINT fk_competency_conduct_behaviors__behavior_catalog_item FOREIGN KEY (behavior_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT ck_competency_conduct_behaviors__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_competency_conduct_behaviors__tenant_conduct_behavior
    ON competency_conduct_behaviors (tenant_id, competency_conduct_id, behavior_catalog_item_id);

CREATE INDEX IF NOT EXISTS ix_competency_conduct_behaviors__tenant_conduct_sort
    ON competency_conduct_behaviors (tenant_id, competency_conduct_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_competency_expectations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    job_profile_id bigint NOT NULL,
    occupational_pyramid_level_id bigint NOT NULL,
    competency_catalog_item_id bigint NOT NULL,
    competency_type_catalog_item_id bigint NOT NULL,
    behavior_level_catalog_item_id bigint NOT NULL,
    expected_evidence character varying(1000),
    sort_order integer NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_competency_expectations PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_competency_expectations__job_profile FOREIGN KEY (job_profile_id) REFERENCES job_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_competency_expectations__pyramid_level FOREIGN KEY (occupational_pyramid_level_id) REFERENCES occupational_pyramid_levels (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_profile_competency_expectations__competency_catalog_item FOREIGN KEY (competency_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_profile_competency_expectations__competency_type_catalog_item FOREIGN KEY (competency_type_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_profile_competency_expectations__behavior_level_catalog_item FOREIGN KEY (behavior_level_catalog_item_id) REFERENCES job_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT ck_job_profile_competency_expectations__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_profile_competency_expectations__public_id
    ON job_profile_competency_expectations (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_profile_competency_expectations__tenant_profile_competency_level
    ON job_profile_competency_expectations (
        tenant_id,
        job_profile_id,
        competency_catalog_item_id,
        competency_type_catalog_item_id,
        behavior_level_catalog_item_id,
        occupational_pyramid_level_id
    );

CREATE INDEX IF NOT EXISTS ix_job_profile_competency_expectations__tenant_profile_sort
    ON job_profile_competency_expectations (tenant_id, job_profile_id, sort_order);

CREATE TABLE IF NOT EXISTS job_profile_competency_expectation_conducts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_profile_competency_expectation_id bigint NOT NULL,
    competency_conduct_id bigint NOT NULL,
    sort_order integer NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_job_profile_competency_expectation_conducts PRIMARY KEY (id),
    CONSTRAINT fk_job_profile_competency_expectation_conducts__expectation FOREIGN KEY (job_profile_competency_expectation_id) REFERENCES job_profile_competency_expectations (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_profile_competency_expectation_conducts__competency_conduct FOREIGN KEY (competency_conduct_id) REFERENCES competency_conducts (id) ON DELETE RESTRICT,
    CONSTRAINT ck_job_profile_competency_expectation_conducts__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_profile_competency_expectation_conducts__tenant_expectation_conduct
    ON job_profile_competency_expectation_conducts (tenant_id, job_profile_competency_expectation_id, competency_conduct_id);

CREATE INDEX IF NOT EXISTS ix_job_profile_competency_expectation_conducts__tenant_expectation_sort
    ON job_profile_competency_expectation_conducts (tenant_id, job_profile_competency_expectation_id, sort_order);

INSERT INTO rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc)
VALUES
    ('COMPETENCY_FRAMEWORK', 'COMPETENCY_FRAMEWORK', 'Competency Framework', true, NOW() AT TIME ZONE 'utc', NOW() AT TIME ZONE 'utc')
ON CONFLICT (resource_key) DO UPDATE
SET normalized_resource_key = EXCLUDED.normalized_resource_key,
    display_name = EXCLUDED.display_name,
    is_active = EXCLUDED.is_active,
    modified_utc = EXCLUDED.modified_utc;

INSERT INTO plan_entitlements (
    plan_code,
    module_key,
    is_enabled,
    created_utc,
    modified_utc)
VALUES
    ('FREE', 'COMPETENCY_FRAMEWORK', true, NOW() AT TIME ZONE 'utc', NOW() AT TIME ZONE 'utc')
ON CONFLICT (plan_code, module_key) DO UPDATE
SET is_enabled = EXCLUDED.is_enabled,
    modified_utc = EXCLUDED.modified_utc;

WITH tenant_source AS (
    SELECT DISTINCT company.public_id AS tenant_id
    FROM companies company
),
permission_source AS (
    SELECT
        source.tenant_id,
        item.code,
        item.name,
        item.description,
        item.module_name,
        item.screen_name,
        item.action_name
    FROM tenant_source source
    CROSS JOIN (
        VALUES
            ('CompetencyFramework.Read', 'Read Competency Framework', 'Read competency framework resources.', 'COMPETENCY_FRAMEWORK', 'CompetencyFramework', 'Read'),
            ('CompetencyFramework.Admin', 'Admin Competency Framework', 'Manage competency framework resources.', 'COMPETENCY_FRAMEWORK', 'CompetencyFramework', 'Manage')
    ) AS item(code, name, description, module_name, screen_name, action_name)
)
INSERT INTO iam_permissions (
    public_id,
    tenant_id,
    code,
    normalized_code,
    name,
    description,
    module,
    normalized_module,
    screen,
    normalized_screen,
    kind,
    action,
    normalized_action,
    field_name,
    normalized_field_name,
    field_access,
    created_utc,
    modified_utc
)
SELECT
    (
        SUBSTRING(MD5(source.tenant_id::text || ':' || UPPER(TRIM(source.code)) || ':public'), 1, 8) || '-' ||
        SUBSTRING(MD5(source.tenant_id::text || ':' || UPPER(TRIM(source.code)) || ':public'), 9, 4) || '-' ||
        SUBSTRING(MD5(source.tenant_id::text || ':' || UPPER(TRIM(source.code)) || ':public'), 13, 4) || '-' ||
        SUBSTRING(MD5(source.tenant_id::text || ':' || UPPER(TRIM(source.code)) || ':public'), 17, 4) || '-' ||
        SUBSTRING(MD5(source.tenant_id::text || ':' || UPPER(TRIM(source.code)) || ':public'), 21, 12)
    )::uuid,
    source.tenant_id,
    source.code,
    UPPER(TRIM(source.code)),
    source.name,
    source.description,
    source.module_name,
    UPPER(TRIM(source.module_name)),
    source.screen_name,
    UPPER(TRIM(source.screen_name)),
    'ScreenAction',
    source.action_name,
    UPPER(TRIM(source.action_name)),
    NULL,
    NULL,
    NULL,
    NOW() AT TIME ZONE 'utc',
    NOW() AT TIME ZONE 'utc'
FROM permission_source source
ON CONFLICT (tenant_id, normalized_code) DO UPDATE
SET code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    module = EXCLUDED.module,
    normalized_module = EXCLUDED.normalized_module,
    screen = EXCLUDED.screen,
    normalized_screen = EXCLUDED.normalized_screen,
    kind = EXCLUDED.kind,
    action = EXCLUDED.action,
    normalized_action = EXCLUDED.normalized_action,
    modified_utc = EXCLUDED.modified_utc;

INSERT INTO iam_role_permission_assignments (
    tenant_id,
    role_id,
    permission_id,
    created_utc,
    modified_utc
)
SELECT
    role.tenant_id,
    role.id,
    target_permission.id,
    NOW() AT TIME ZONE 'utc',
    NOW() AT TIME ZONE 'utc'
FROM iam_roles role
JOIN iam_permissions manage_permission
    ON manage_permission.tenant_id = role.tenant_id
   AND manage_permission.normalized_code = 'IAM.ADMINISTRATION.MANAGE'
JOIN iam_role_permission_assignments manage_assignment
    ON manage_assignment.tenant_id = role.tenant_id
   AND manage_assignment.role_id = role.id
   AND manage_assignment.permission_id = manage_permission.id
JOIN iam_permissions target_permission
    ON target_permission.tenant_id = role.tenant_id
   AND target_permission.normalized_code IN ('COMPETENCYFRAMEWORK.READ', 'COMPETENCYFRAMEWORK.ADMIN')
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_role_permission_assignments existing
    WHERE existing.tenant_id = role.tenant_id
      AND existing.role_id = role.id
      AND existing.permission_id = target_permission.id
);
