-- HU-014 - Salary tabulator and change requests

CREATE TABLE IF NOT EXISTS salary_tabulator_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    salary_class_code character varying(50) NOT NULL,
    normalized_salary_class_code character varying(50) NOT NULL,
    salary_scale_code character varying(50) NOT NULL,
    normalized_salary_scale_code character varying(50) NOT NULL,
    currency_code character varying(3) NOT NULL,
    base_amount numeric(18, 2) NOT NULL,
    min_amount numeric(18, 2),
    max_amount numeric(18, 2),
    effective_from_utc timestamp with time zone NOT NULL,
    effective_to_utc timestamp with time zone,
    is_active boolean NOT NULL,
    version integer NOT NULL,
    notes character varying(2000),
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_salary_tabulator_lines PRIMARY KEY (id),
    CONSTRAINT ck_salary_tabulator_lines__base_positive CHECK (base_amount > 0),
    CONSTRAINT ck_salary_tabulator_lines__min_max CHECK (min_amount IS NULL OR max_amount IS NULL OR min_amount <= max_amount),
    CONSTRAINT ck_salary_tabulator_lines__date_range CHECK (effective_to_utc IS NULL OR effective_to_utc >= effective_from_utc)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_salary_tabulator_lines__public_id
    ON salary_tabulator_lines (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_salary_tabulator_lines__tenant_class_scale_effective_from
    ON salary_tabulator_lines (tenant_id, normalized_salary_class_code, normalized_salary_scale_code, effective_from_utc);

CREATE INDEX IF NOT EXISTS ix_salary_tabulator_lines__tenant_class_scale_active
    ON salary_tabulator_lines (tenant_id, normalized_salary_class_code, normalized_salary_scale_code, is_active);

CREATE TABLE IF NOT EXISTS salary_tabulator_change_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    request_number character varying(40) NOT NULL,
    reason character varying(1000) NOT NULL,
    status character varying(20) NOT NULL,
    effective_from_utc timestamp with time zone NOT NULL,
    requested_by_user_id uuid NOT NULL,
    submitted_at_utc timestamp with time zone,
    decided_by_user_id uuid,
    decided_at_utc timestamp with time zone,
    decision_comment character varying(1000),
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_salary_tabulator_change_requests PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_salary_tabulator_change_requests__public_id
    ON salary_tabulator_change_requests (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS ix_salary_tabulator_requests__tenant_request_number
    ON salary_tabulator_change_requests (tenant_id, request_number);

CREATE INDEX IF NOT EXISTS ix_salary_tabulator_requests__tenant_status_created
    ON salary_tabulator_change_requests (tenant_id, status, created_utc);

CREATE TABLE IF NOT EXISTS salary_tabulator_change_request_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    salary_tabulator_change_request_id bigint NOT NULL,
    salary_class_code character varying(50) NOT NULL,
    normalized_salary_class_code character varying(50) NOT NULL,
    salary_scale_code character varying(50) NOT NULL,
    normalized_salary_scale_code character varying(50) NOT NULL,
    currency_code character varying(3) NOT NULL,
    change_type character varying(20) NOT NULL,
    current_base_amount numeric(18, 2),
    proposed_base_amount numeric(18, 2),
    current_min_amount numeric(18, 2),
    proposed_min_amount numeric(18, 2),
    current_max_amount numeric(18, 2),
    proposed_max_amount numeric(18, 2),
    notes character varying(1000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_salary_tabulator_change_request_items PRIMARY KEY (id),
    CONSTRAINT fk_salary_tabulator_change_request_items__request FOREIGN KEY (salary_tabulator_change_request_id)
        REFERENCES salary_tabulator_change_requests (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_salary_tabulator_items__request
    ON salary_tabulator_change_request_items (salary_tabulator_change_request_id);
