-- HU-010 - Locations hierarchy, groups, work center types and work centers

CREATE TABLE IF NOT EXISTS location_hierarchy_configs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    is_multi_level boolean NOT NULL,
    default_group_code character varying(50) NOT NULL,
    default_group_name character varying(150) NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_location_hierarchy_configs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS location_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    level_order integer NOT NULL,
    display_name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    is_required boolean NOT NULL,
    allows_work_centers boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_location_levels PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS location_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    level_order integer NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    parent_id bigint,
    description character varying(500),
    is_active boolean NOT NULL,
    is_default boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_location_groups PRIMARY KEY (id),
    CONSTRAINT fk_location_groups__parent FOREIGN KEY (parent_id) REFERENCES location_groups (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS work_center_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    requires_address boolean NOT NULL,
    requires_geo boolean NOT NULL,
    allows_biometric boolean NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_work_center_types PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS work_centers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    work_center_type_id bigint NOT NULL,
    location_group_id bigint NOT NULL,
    address character varying(300),
    geo_lat numeric(9,6),
    geo_long numeric(9,6),
    phone character varying(50),
    email character varying(200),
    notes character varying(1000),
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_work_centers PRIMARY KEY (id),
    CONSTRAINT fk_work_centers__location_groups FOREIGN KEY (location_group_id) REFERENCES location_groups (id) ON DELETE RESTRICT,
    CONSTRAINT fk_work_centers__work_center_types FOREIGN KEY (work_center_type_id) REFERENCES work_center_types (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_hierarchy_configs__public_id
    ON location_hierarchy_configs (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_hierarchy_configs__tenant_id
    ON location_hierarchy_configs (tenant_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_levels__public_id
    ON location_levels (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_levels__tenant_order
    ON location_levels (tenant_id, level_order);

CREATE INDEX IF NOT EXISTS ix_location_levels__tenant_active_order
    ON location_levels (tenant_id, is_active, level_order);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_groups__public_id
    ON location_groups (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_groups__tenant_code
    ON location_groups (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_location_groups__tenant_parent_name
    ON location_groups (tenant_id, parent_id, normalized_name);

CREATE INDEX IF NOT EXISTS ix_location_groups__tenant_level_active
    ON location_groups (tenant_id, level_order, is_active);

CREATE INDEX IF NOT EXISTS ix_location_groups__tenant_parent_active
    ON location_groups (tenant_id, parent_id, is_active);

CREATE INDEX IF NOT EXISTS ix_location_groups__tenant_name
    ON location_groups (tenant_id, normalized_name);

CREATE UNIQUE INDEX IF NOT EXISTS uq_work_center_types__public_id
    ON work_center_types (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_work_center_types__tenant_code
    ON work_center_types (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_work_center_types__tenant_active
    ON work_center_types (tenant_id, is_active);

CREATE INDEX IF NOT EXISTS ix_work_center_types__tenant_name
    ON work_center_types (tenant_id, normalized_name);

CREATE UNIQUE INDEX IF NOT EXISTS uq_work_centers__public_id
    ON work_centers (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_work_centers__tenant_code
    ON work_centers (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_work_centers__tenant_group_active
    ON work_centers (tenant_id, location_group_id, is_active);

CREATE INDEX IF NOT EXISTS ix_work_centers__tenant_type_active
    ON work_centers (tenant_id, work_center_type_id, is_active);

CREATE INDEX IF NOT EXISTS ix_work_centers__tenant_name
    ON work_centers (tenant_id, normalized_name);
