-- HU-015 - Cost centers and accounting references

CREATE TABLE IF NOT EXISTS cost_centers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    type character varying(40) NOT NULL,
    payroll_expense_account_code character varying(100),
    employer_contribution_account_code character varying(100),
    provision_account_code character varying(100),
    description character varying(500),
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_cost_centers PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cost_centers__public_id
    ON cost_centers (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cost_centers__tenant_code
    ON cost_centers (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_cost_centers__tenant_type_active
    ON cost_centers (tenant_id, type, is_active);

CREATE INDEX IF NOT EXISTS ix_cost_centers__tenant_normalized_name
    ON cost_centers (tenant_id, normalized_name);

WITH source_codes AS (
    SELECT DISTINCT
        tenant_id,
        BTRIM(cost_center_code) AS code,
        UPPER(BTRIM(cost_center_code)) AS normalized_code
    FROM org_units
    WHERE cost_center_code IS NOT NULL
      AND BTRIM(cost_center_code) <> ''
    UNION
    SELECT DISTINCT
        tenant_id,
        BTRIM(cost_center_code) AS code,
        UPPER(BTRIM(cost_center_code)) AS normalized_code
    FROM position_slots
    WHERE cost_center_code IS NOT NULL
      AND BTRIM(cost_center_code) <> ''
),
missing_codes AS (
    SELECT source.*
    FROM source_codes source
    LEFT JOIN cost_centers existing
        ON existing.tenant_id = source.tenant_id
       AND existing.normalized_code = source.normalized_code
    WHERE existing.id IS NULL
)
INSERT INTO cost_centers
(
    public_id,
    code,
    normalized_code,
    name,
    normalized_name,
    type,
    payroll_expense_account_code,
    employer_contribution_account_code,
    provision_account_code,
    description,
    is_active,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    (
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':public'), 1, 8) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':public'), 9, 4) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':public'), 13, 4) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':public'), 17, 4) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':public'), 21, 12)
    )::uuid,
    missing.code,
    missing.normalized_code,
    missing.code,
    missing.normalized_code,
    'Mixed',
    NULL,
    NULL,
    NULL,
    'Backfilled from existing OrgUnits/PositionSlots references.',
    TRUE,
    (
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':token'), 1, 8) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':token'), 9, 4) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':token'), 13, 4) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':token'), 17, 4) || '-' ||
        SUBSTRING(MD5(missing.tenant_id::text || ':' || missing.normalized_code || ':token'), 21, 12)
    )::uuid,
    NOW(),
    NOW(),
    missing.tenant_id
FROM missing_codes missing;
