-- HU-011 - Organization units (org chart)

CREATE TABLE IF NOT EXISTS org_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    unit_type character varying(50) NOT NULL,
    parent_id bigint,
    sort_order integer,
    description character varying(500),
    cost_center_code character varying(100),
    manager_employee_id uuid,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_org_units PRIMARY KEY (id),
    CONSTRAINT fk_org_units__parent FOREIGN KEY (parent_id) REFERENCES org_units (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_units__public_id
    ON org_units (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_units__tenant_code
    ON org_units (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_org_units__tenant_parent
    ON org_units (tenant_id, parent_id);

CREATE INDEX IF NOT EXISTS ix_org_units__tenant_active
    ON org_units (tenant_id, is_active);

CREATE INDEX IF NOT EXISTS ix_org_units__tenant_name
    ON org_units (tenant_id, normalized_name);
