-- HU-024 - Personnel file documents, custom fields, and observations

CREATE TABLE IF NOT EXISTS personnel_file_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    document_type character varying(100) NOT NULL,
    observations character varying(2000),
    delivery_date timestamp with time zone,
    loan_date timestamp with time zone,
    return_date timestamp with time zone,
    file_name character varying(260) NOT NULL,
    content_type character varying(200) NOT NULL,
    size_bytes integer NOT NULL,
    sha256 character varying(64) NOT NULL,
    file_data bytea NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_documents PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_documents__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_documents__loan_return
        CHECK (return_date IS NULL OR loan_date IS NULL OR return_date >= loan_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_documents__public_id
    ON personnel_file_documents (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_documents__tenant_file_active
    ON personnel_file_documents (tenant_id, personnel_file_id, is_active);

CREATE TABLE IF NOT EXISTS personnel_file_custom_field_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    key character varying(80) NOT NULL,
    normalized_key character varying(80) NOT NULL,
    label character varying(200) NOT NULL,
    field_type character varying(20) NOT NULL,
    is_required boolean NOT NULL,
    is_active boolean NOT NULL,
    options_json jsonb,
    sort_order integer NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_custom_field_definitions PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_custom_field_definitions__public_id
    ON personnel_file_custom_field_definitions (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_custom_field_definitions__tenant_key
    ON personnel_file_custom_field_definitions (tenant_id, normalized_key);

CREATE INDEX IF NOT EXISTS ix_personnel_file_custom_field_definitions__tenant_active_sort
    ON personnel_file_custom_field_definitions (tenant_id, is_active, sort_order);

CREATE TABLE IF NOT EXISTS personnel_file_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    author_user_public_id uuid NOT NULL,
    note character varying(4000) NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_observations PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_observations__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_observations__public_id
    ON personnel_file_observations (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_observations__tenant_file_created
    ON personnel_file_observations (tenant_id, personnel_file_id, created_utc);
