-- HU-020 - Position description catalogs (i-xiv)

CREATE TABLE IF NOT EXISTS position_description_catalog_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    catalog_type character varying(50) NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    description character varying(500),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    CONSTRAINT pk_position_description_catalog_items PRIMARY KEY (id),
    CONSTRAINT ck_position_description_catalog_items__sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_description_catalog_items__public_id
    ON position_description_catalog_items (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_description_catalog_items__tenant_type_code
    ON position_description_catalog_items (tenant_id, catalog_type, normalized_code);

CREATE INDEX IF NOT EXISTS ix_position_description_catalog_items__tenant_type_name
    ON position_description_catalog_items (tenant_id, catalog_type, normalized_name);

CREATE INDEX IF NOT EXISTS ix_position_description_catalog_items__tenant_type_active
    ON position_description_catalog_items (tenant_id, catalog_type, is_active);

CREATE TABLE IF NOT EXISTS position_category_classifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    description character varying(500),
    position_function_catalog_item_id bigint NOT NULL,
    position_contract_catalog_item_id bigint NOT NULL,
    org_unit_type_catalog_item_id bigint NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    CONSTRAINT pk_position_category_classifications PRIMARY KEY (id),
    CONSTRAINT ck_position_category_classifications__sort_order CHECK (sort_order >= 0),
    CONSTRAINT fk_position_category_classifications__position_function_catalog_item
        FOREIGN KEY (position_function_catalog_item_id) REFERENCES position_description_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_category_classifications__position_contract_catalog_item
        FOREIGN KEY (position_contract_catalog_item_id) REFERENCES position_description_catalog_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_position_category_classifications__org_unit_type_catalog_item
        FOREIGN KEY (org_unit_type_catalog_item_id) REFERENCES org_unit_type_catalog_items (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_category_classifications__public_id
    ON position_category_classifications (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_category_classifications__tenant_code
    ON position_category_classifications (tenant_id, normalized_code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_category_classifications__tenant_axes
    ON position_category_classifications (
        tenant_id,
        position_function_catalog_item_id,
        position_contract_catalog_item_id,
        org_unit_type_catalog_item_id
    );

CREATE INDEX IF NOT EXISTS ix_position_category_classifications__tenant_name
    ON position_category_classifications (tenant_id, normalized_name);

CREATE INDEX IF NOT EXISTS ix_position_category_classifications__tenant_active
    ON position_category_classifications (tenant_id, is_active);

CREATE TABLE IF NOT EXISTS position_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    code character varying(50) NOT NULL,
    normalized_code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    description character varying(500),
    position_category_classification_id bigint NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    CONSTRAINT pk_position_categories PRIMARY KEY (id),
    CONSTRAINT ck_position_categories__sort_order CHECK (sort_order >= 0),
    CONSTRAINT fk_position_categories__position_category_classification
        FOREIGN KEY (position_category_classification_id) REFERENCES position_category_classifications (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_categories__public_id
    ON position_categories (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_categories__tenant_code
    ON position_categories (tenant_id, normalized_code);

CREATE INDEX IF NOT EXISTS ix_position_categories__tenant_classification
    ON position_categories (tenant_id, position_category_classification_id);

CREATE INDEX IF NOT EXISTS ix_position_categories__tenant_name
    ON position_categories (tenant_id, normalized_name);

CREATE INDEX IF NOT EXISTS ix_position_categories__tenant_active
    ON position_categories (tenant_id, is_active);

INSERT INTO rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc
)
VALUES (
    'POSITION_DESCRIPTION_CATALOGS',
    'POSITION_DESCRIPTION_CATALOGS',
    'Position Description Catalogs',
    true,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
)
ON CONFLICT (resource_key) DO UPDATE
SET normalized_resource_key = EXCLUDED.normalized_resource_key,
    display_name = EXCLUDED.display_name,
    is_active = EXCLUDED.is_active,
    modified_utc = EXCLUDED.modified_utc;

INSERT INTO plan_entitlements (
    plan_code,
    module_key,
    is_enabled,
    created_utc,
    modified_utc
)
VALUES (
    'FREE',
    'POSITION_DESCRIPTION_CATALOGS',
    true,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
)
ON CONFLICT (plan_code, module_key) DO UPDATE
SET is_enabled = EXCLUDED.is_enabled,
    modified_utc = EXCLUDED.modified_utc;

WITH tenants AS (
    SELECT DISTINCT tenant_id
    FROM iam_roles
),
permission_source AS (
    SELECT
        tenant_id,
        code,
        upper(code) AS normalized_code,
        name,
        description,
        module_name,
        upper(module_name) AS normalized_module,
        screen_name,
        upper(screen_name) AS normalized_screen,
        action_name,
        upper(action_name) AS normalized_action
    FROM tenants
    CROSS JOIN (
        VALUES
            ('PositionDescriptionCatalogs.Read', 'Read Position Description Catalogs', 'Read position description catalogs.', 'POSITION_DESCRIPTION_CATALOGS', 'PositionDescriptionCatalogs', 'Read'),
            ('PositionDescriptionCatalogs.Admin', 'Admin Position Description Catalogs', 'Manage position description catalogs.', 'POSITION_DESCRIPTION_CATALOGS', 'PositionDescriptionCatalogs', 'Manage')
    ) AS source(code, name, description, module_name, screen_name, action_name)
)
INSERT INTO iam_permissions (
    public_id,
    tenant_id,
    code,
    normalized_code,
    name,
    description,
    module,
    normalized_module,
    screen,
    normalized_screen,
    kind,
    action,
    normalized_action,
    field_name,
    normalized_field_name,
    field_access,
    created_utc,
    modified_utc
)
SELECT
    gen_random_uuid(),
    source.tenant_id,
    source.code,
    source.normalized_code,
    source.name,
    source.description,
    source.module_name,
    source.normalized_module,
    source.screen_name,
    source.normalized_screen,
    'Action',
    source.action_name,
    source.normalized_action,
    NULL,
    NULL,
    NULL,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
FROM permission_source source
ON CONFLICT (tenant_id, normalized_code) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    module = EXCLUDED.module,
    normalized_module = EXCLUDED.normalized_module,
    screen = EXCLUDED.screen,
    normalized_screen = EXCLUDED.normalized_screen,
    kind = EXCLUDED.kind,
    action = EXCLUDED.action,
    normalized_action = EXCLUDED.normalized_action,
    field_name = EXCLUDED.field_name,
    normalized_field_name = EXCLUDED.normalized_field_name,
    field_access = EXCLUDED.field_access,
    modified_utc = EXCLUDED.modified_utc;

WITH admin_manage_permissions AS (
    SELECT tenant_id, id
    FROM iam_permissions
    WHERE normalized_code = 'IAM.ADMINISTRATION.MANAGE'
),
admin_roles AS (
    SELECT DISTINCT
        assignment.tenant_id,
        assignment.role_id
    FROM iam_role_permission_assignments assignment
    JOIN admin_manage_permissions permission
      ON permission.tenant_id = assignment.tenant_id
     AND permission.id = assignment.permission_id
),
module_permissions AS (
    SELECT tenant_id, id
    FROM iam_permissions
    WHERE normalized_code IN ('POSITIONDESCRIPTIONCATALOGS.READ', 'POSITIONDESCRIPTIONCATALOGS.ADMIN')
)
INSERT INTO iam_role_permission_assignments (
    tenant_id,
    role_id,
    permission_id,
    created_utc,
    modified_utc
)
SELECT
    role.tenant_id,
    role.role_id,
    permission.id,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
FROM admin_roles role
JOIN module_permissions permission
  ON permission.tenant_id = role.tenant_id
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_role_permission_assignments existing
    WHERE existing.tenant_id = role.tenant_id
      AND existing.role_id = role.role_id
      AND existing.permission_id = permission.id
);
