-- HU-029 - Personnel files employee operations

CREATE TABLE IF NOT EXISTS personnel_file_personnel_actions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    action_type_code character varying(80) NOT NULL,
    action_status_code character varying(80) NOT NULL,
    action_date_utc timestamp with time zone NOT NULL,
    effective_from_utc timestamp with time zone,
    effective_to_utc timestamp with time zone,
    description character varying(2000),
    reference character varying(120),
    amount numeric(18,2),
    currency_code character varying(40),
    is_system_generated boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_personnel_actions PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_personnel_actions__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_personnel_actions__public_id
    ON personnel_file_personnel_actions (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_personnel_actions__tenant_file_action_date
    ON personnel_file_personnel_actions (tenant_id, personnel_file_id, action_date_utc);

CREATE INDEX IF NOT EXISTS ix_personnel_file_personnel_actions__tenant_file_type_status
    ON personnel_file_personnel_actions (tenant_id, personnel_file_id, action_type_code, action_status_code);

CREATE TABLE IF NOT EXISTS personnel_file_payroll_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    transaction_type_code character varying(80) NOT NULL,
    transaction_date_utc timestamp with time zone NOT NULL,
    payroll_period_code character varying(80) NOT NULL,
    description character varying(2000),
    amount numeric(18,2) NOT NULL,
    currency_code character varying(40) NOT NULL,
    is_debit boolean NOT NULL,
    source_system character varying(80),
    source_reference character varying(120),
    source_synced_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_payroll_transactions PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_payroll_transactions__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_payroll_transactions__public_id
    ON personnel_file_payroll_transactions (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_payroll_transactions__tenant_file_transaction_date
    ON personnel_file_payroll_transactions (tenant_id, personnel_file_id, transaction_date_utc);

CREATE INDEX IF NOT EXISTS ix_personnel_file_payroll_transactions__tenant_file_type
    ON personnel_file_payroll_transactions (tenant_id, personnel_file_id, transaction_type_code);

CREATE TABLE IF NOT EXISTS personnel_file_assets_accesses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    asset_type_code character varying(80) NOT NULL,
    asset_or_access_name character varying(200) NOT NULL,
    access_level_code character varying(80),
    start_date_utc timestamp with time zone NOT NULL,
    end_date_utc timestamp with time zone,
    delivery_date_utc timestamp with time zone,
    delivery_status_code character varying(80),
    is_active boolean NOT NULL,
    notes character varying(2000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_assets_accesses PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_assets_accesses__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_assets_accesses__public_id
    ON personnel_file_assets_accesses (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_assets_accesses__tenant_file_start_active
    ON personnel_file_assets_accesses (tenant_id, personnel_file_id, start_date_utc, is_active);

CREATE TABLE IF NOT EXISTS personnel_file_insurances (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    insurance_code character varying(80) NOT NULL,
    employee_contribution numeric(18,2),
    employer_contribution numeric(18,2),
    range_code character varying(80),
    policy_number character varying(120),
    insured_amount numeric(18,2),
    currency_code character varying(40),
    is_active boolean NOT NULL,
    start_date_utc timestamp with time zone,
    end_date_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_insurances PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_insurances__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_insurances__public_id
    ON personnel_file_insurances (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_insurances__tenant_file_active_code
    ON personnel_file_insurances (tenant_id, personnel_file_id, is_active, insurance_code);

CREATE TABLE IF NOT EXISTS personnel_file_insurance_beneficiaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    insurance_id bigint NOT NULL,
    full_name character varying(200) NOT NULL,
    document_number character varying(80),
    birth_date timestamp with time zone,
    kinship_code character varying(80) NOT NULL,
    is_active boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_insurance_beneficiaries PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_insurance_beneficiaries__insurance
        FOREIGN KEY (insurance_id)
        REFERENCES personnel_file_insurances (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_insurance_beneficiaries__public_id
    ON personnel_file_insurance_beneficiaries (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_insurance_beneficiaries__tenant_insurance_active
    ON personnel_file_insurance_beneficiaries (tenant_id, insurance_id, is_active);

CREATE TABLE IF NOT EXISTS personnel_file_medical_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    insurance_public_id uuid,
    account_number character varying(120),
    claim_type_code character varying(80) NOT NULL,
    diagnosis character varying(1000),
    claim_amount numeric(18,2),
    currency_code character varying(40),
    paid_amount numeric(18,2),
    response_time_days integer,
    notes character varying(2000),
    claim_date_utc timestamp with time zone NOT NULL,
    source_system character varying(80),
    source_reference character varying(120),
    source_synced_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_medical_claims PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_medical_claims__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_medical_claims__public_id
    ON personnel_file_medical_claims (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_medical_claims__tenant_file_date_type
    ON personnel_file_medical_claims (tenant_id, personnel_file_id, claim_date_utc, claim_type_code);

WITH tenant_source AS (
    SELECT DISTINCT public_id AS tenant_id
    FROM companies
), catalog_source AS (
    SELECT * FROM (VALUES
        ('EmploymentPersonnelActionType', 'SALARY_INCREMENT', 'Incremento salarial', 10),
        ('EmploymentPersonnelActionType', 'CONTRACT_CHANGE', 'Cambio de contrato', 20),
        ('EmploymentPersonnelActionType', 'TRANSFER', 'Traslado', 30),
        ('EmploymentPersonnelActionStatus', 'APPLIED', 'Aplicado', 10),
        ('EmploymentPersonnelActionStatus', 'PENDING', 'Pendiente', 20),
        ('EmploymentPayrollTransactionType', 'EARNING', 'Ingreso', 10),
        ('EmploymentPayrollTransactionType', 'DEDUCTION', 'Descuento', 20),
        ('EmploymentAssetType', 'LAPTOP', 'Computadora', 10),
        ('EmploymentAccessLevel', 'STANDARD', 'Estandar', 10),
        ('EmploymentInsurance', 'MEDICAL', 'Seguro medico', 10),
        ('EmploymentInsuranceRange', 'FAMILY', 'Familiar', 10),
        ('EmploymentKinship', 'SPOUSE', 'Conyuge', 10),
        ('EmploymentMedicalClaimType', 'OUTPATIENT', 'Consulta externa', 10)
    ) AS source(category, code, name, sort_order)
)
INSERT INTO personnel_catalog_items (
    public_id,
    category,
    code,
    normalized_code,
    name,
    normalized_name,
    is_system,
    is_active,
    sort_order,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    gen_random_uuid(),
    catalog.category,
    catalog.code,
    upper(catalog.code),
    catalog.name,
    upper(catalog.name),
    true,
    true,
    catalog.sort_order,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    tenant.tenant_id
FROM tenant_source tenant
CROSS JOIN catalog_source catalog
ON CONFLICT (tenant_id, category, normalized_code) DO UPDATE
SET name = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    is_system = EXCLUDED.is_system,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    modified_utc = EXCLUDED.modified_utc;
