-- HU-026 - Personnel files curriculum sections

CREATE TABLE IF NOT EXISTS personnel_file_educations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    status_code character varying(80) NOT NULL,
    degree_title character varying(200),
    study_type_code character varying(80) NOT NULL,
    career character varying(200) NOT NULL,
    institution character varying(200) NOT NULL,
    country_code character varying(80) NOT NULL,
    specialty character varying(200),
    is_currently_studying boolean NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    shift_code character varying(80),
    modality_code character varying(80),
    total_subjects integer,
    approved_subjects integer,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_educations PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_educations__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_educations__dates
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_personnel_file_educations__active_end_date
        CHECK (is_currently_studying = TRUE OR end_date IS NOT NULL),
    CONSTRAINT ck_personnel_file_educations__total_subjects_non_negative
        CHECK (total_subjects IS NULL OR total_subjects >= 0),
    CONSTRAINT ck_personnel_file_educations__approved_subjects_non_negative
        CHECK (approved_subjects IS NULL OR approved_subjects >= 0),
    CONSTRAINT ck_personnel_file_educations__approved_subjects_range
        CHECK (
            total_subjects IS NULL
            OR approved_subjects IS NULL
            OR approved_subjects <= total_subjects
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_educations__public_id
    ON personnel_file_educations (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_educations__tenant_file
    ON personnel_file_educations (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_languages (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    language_code character varying(80) NOT NULL,
    level_code character varying(80) NOT NULL,
    speaks boolean NOT NULL,
    writes boolean NOT NULL,
    reads boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_languages PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_languages__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_languages__skills
        CHECK (speaks = TRUE OR writes = TRUE OR reads = TRUE)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_languages__public_id
    ON personnel_file_languages (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_languages__tenant_file
    ON personnel_file_languages (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_trainings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    training_name character varying(200) NOT NULL,
    training_type_code character varying(80) NOT NULL,
    description character varying(1000),
    topic character varying(200),
    institution character varying(200),
    instructors character varying(500),
    score numeric(10,2),
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    is_internal boolean NOT NULL,
    is_local boolean NOT NULL,
    country_code character varying(80) NOT NULL,
    duration_value numeric(10,2) NOT NULL,
    duration_unit_code character varying(80) NOT NULL,
    cost_amount numeric(18,2),
    cost_currency_code character varying(40),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_trainings PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_trainings__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_trainings__dates
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_personnel_file_trainings__duration
        CHECK (duration_value > 0),
    CONSTRAINT ck_personnel_file_trainings__cost_non_negative
        CHECK (cost_amount IS NULL OR cost_amount >= 0),
    CONSTRAINT ck_personnel_file_trainings__cost_currency
        CHECK (cost_amount IS NULL OR cost_currency_code IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_trainings__public_id
    ON personnel_file_trainings (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_trainings__tenant_file
    ON personnel_file_trainings (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_previous_employments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    institution character varying(200) NOT NULL,
    place character varying(200),
    last_position character varying(150),
    manager_name character varying(150),
    entry_date timestamp with time zone NOT NULL,
    retirement_date timestamp with time zone,
    company_phone character varying(40),
    exit_reason character varying(500),
    first_salary_amount numeric(18,2),
    last_salary_amount numeric(18,2),
    average_commission_amount numeric(18,2),
    currency_code character varying(40) NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_previous_employments PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_previous_employments__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_previous_employments__dates
        CHECK (retirement_date IS NULL OR retirement_date >= entry_date),
    CONSTRAINT ck_personnel_file_previous_employments__first_salary_non_negative
        CHECK (first_salary_amount IS NULL OR first_salary_amount >= 0),
    CONSTRAINT ck_personnel_file_previous_employments__last_salary_non_negative
        CHECK (last_salary_amount IS NULL OR last_salary_amount >= 0),
    CONSTRAINT ck_personnel_file_previous_employments__commission_non_negative
        CHECK (average_commission_amount IS NULL OR average_commission_amount >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_previous_employments__public_id
    ON personnel_file_previous_employments (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_previous_employments__tenant_file
    ON personnel_file_previous_employments (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_references (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    person_name character varying(150) NOT NULL,
    address character varying(500),
    phone character varying(40) NOT NULL,
    reference_type_code character varying(80) NOT NULL,
    occupation character varying(120),
    workplace character varying(200),
    work_phone character varying(40),
    known_time_years numeric(10,2) NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_references PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_references__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_references__known_time_non_negative
        CHECK (known_time_years >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_references__public_id
    ON personnel_file_references (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_references__tenant_file
    ON personnel_file_references (tenant_id, personnel_file_id);

WITH tenant_source AS (
    SELECT DISTINCT public_id AS tenant_id
    FROM companies
), catalog_source AS (
    SELECT * FROM (VALUES
        ('CurriculumEducationStatus', 'GRADUATED', 'Graduated', 10),
        ('CurriculumEducationStatus', 'PAUSED', 'Paused', 20),
        ('CurriculumEducationStatus', 'IN_PROGRESS', 'In progress', 30),
        ('CurriculumStudyType', 'TECHNICAL', 'Technical', 10),
        ('CurriculumStudyType', 'BACHELOR', 'Bachelor', 20),
        ('CurriculumStudyType', 'MASTER', 'Master', 30),
        ('CurriculumStudyType', 'DOCTORATE', 'Doctorate', 40),
        ('CurriculumShift', 'MORNING', 'Morning', 10),
        ('CurriculumShift', 'AFTERNOON', 'Afternoon', 20),
        ('CurriculumShift', 'EVENING', 'Evening', 30),
        ('CurriculumShift', 'WEEKEND', 'Weekend', 40),
        ('CurriculumModality', 'ONSITE', 'Onsite', 10),
        ('CurriculumModality', 'ONLINE', 'Online', 20),
        ('CurriculumModality', 'HYBRID', 'Hybrid', 30),
        ('CurriculumLanguage', 'SPANISH', 'Spanish', 10),
        ('CurriculumLanguage', 'ENGLISH', 'English', 20),
        ('CurriculumLanguage', 'FRENCH', 'French', 30),
        ('CurriculumLanguage', 'PORTUGUESE', 'Portuguese', 40),
        ('CurriculumLanguageLevel', 'BASIC', 'Basic', 10),
        ('CurriculumLanguageLevel', 'INTERMEDIATE', 'Intermediate', 20),
        ('CurriculumLanguageLevel', 'ADVANCED', 'Advanced', 30),
        ('CurriculumLanguageLevel', 'NATIVE', 'Native', 40),
        ('CurriculumTrainingType', 'COURSE', 'Course', 10),
        ('CurriculumTrainingType', 'CERTIFICATION', 'Certification', 20),
        ('CurriculumTrainingType', 'WORKSHOP', 'Workshop', 30),
        ('CurriculumTrainingType', 'SEMINAR', 'Seminar', 40),
        ('CurriculumDurationUnit', 'HOUR', 'Hour', 10),
        ('CurriculumDurationUnit', 'DAY', 'Day', 20),
        ('CurriculumDurationUnit', 'WEEK', 'Week', 30),
        ('CurriculumDurationUnit', 'MONTH', 'Month', 40),
        ('CurriculumDurationUnit', 'YEAR', 'Year', 50),
        ('CurriculumReferenceType', 'PERSONAL', 'Personal', 10),
        ('CurriculumReferenceType', 'LABOR', 'Labor', 20),
        ('Country', 'SV', 'El Salvador', 10),
        ('Country', 'GT', 'Guatemala', 20),
        ('Country', 'HN', 'Honduras', 30),
        ('Country', 'NI', 'Nicaragua', 40),
        ('Country', 'CR', 'Costa Rica', 50),
        ('Country', 'PA', 'Panama', 60),
        ('Country', 'MX', 'Mexico', 70),
        ('Country', 'US', 'United States', 80)
    ) AS source(category, code, name, sort_order)
)
INSERT INTO personnel_catalog_items (
    public_id,
    category,
    code,
    normalized_code,
    name,
    normalized_name,
    is_system,
    is_active,
    sort_order,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    gen_random_uuid(),
    catalog.category,
    catalog.code,
    upper(catalog.code),
    catalog.name,
    upper(catalog.name),
    true,
    true,
    catalog.sort_order,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    tenant.tenant_id
FROM tenant_source tenant
CROSS JOIN catalog_source catalog
ON CONFLICT (tenant_id, category, normalized_code) DO UPDATE
SET name = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    is_system = EXCLUDED.is_system,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    modified_utc = EXCLUDED.modified_utc;
