-- HU-028 - Personnel files employee core

CREATE TABLE IF NOT EXISTS personnel_file_employee_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    employee_code character varying(80) NOT NULL,
    normalized_employee_code character varying(80) NOT NULL,
    employment_status_code character varying(80) NOT NULL,
    is_employment_active boolean NOT NULL,
    contract_type_code character varying(80) NOT NULL,
    hire_date timestamp with time zone NOT NULL,
    retirement_category_code character varying(80),
    retirement_reason_code character varying(80),
    retirement_notes character varying(2000),
    retirement_date timestamp with time zone,
    workday_code character varying(80),
    payroll_type_code character varying(80),
    position_slot_public_id uuid,
    job_profile_public_id uuid,
    org_unit_public_id uuid,
    work_center_public_id uuid,
    cost_center_public_id uuid,
    contract_start_date timestamp with time zone,
    contract_end_date timestamp with time zone,
    vacation_configuration_json jsonb,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_employee_profiles PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_employee_profiles__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_employee_profiles__contract_dates
        CHECK (contract_end_date IS NULL OR contract_start_date IS NULL OR contract_end_date >= contract_start_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_employee_profiles__public_id
    ON personnel_file_employee_profiles (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_employee_profiles__tenant_employee_code
    ON personnel_file_employee_profiles (tenant_id, normalized_employee_code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_employee_profiles__tenant_file
    ON personnel_file_employee_profiles (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_employment_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    assignment_type_code character varying(80) NOT NULL,
    position_slot_public_id uuid,
    org_unit_public_id uuid,
    work_center_public_id uuid,
    cost_center_public_id uuid,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    notes character varying(2000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_employment_assignments PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_employment_assignments__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_employment_assignments__dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_employment_assignments__public_id
    ON personnel_file_employment_assignments (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_employment_assignments__tenant_file_start
    ON personnel_file_employment_assignments (tenant_id, personnel_file_id, start_date);

CREATE INDEX IF NOT EXISTS ix_personnel_file_employment_assignments__tenant_file_active_primary
    ON personnel_file_employment_assignments (tenant_id, personnel_file_id, is_active, is_primary);

CREATE TABLE IF NOT EXISTS personnel_file_contract_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    contract_type_code character varying(80) NOT NULL,
    contract_date timestamp with time zone NOT NULL,
    contract_end_date timestamp with time zone,
    position_slot_public_id uuid,
    notes character varying(2000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_contract_histories PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_contract_histories__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_contract_histories__dates
        CHECK (contract_end_date IS NULL OR contract_end_date >= contract_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_contract_histories__public_id
    ON personnel_file_contract_histories (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_contract_histories__tenant_file_contract_date
    ON personnel_file_contract_histories (tenant_id, personnel_file_id, contract_date);

CREATE TABLE IF NOT EXISTS personnel_file_salary_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    income_type_code character varying(80) NOT NULL,
    salary_rubric_code character varying(80) NOT NULL,
    currency_code character varying(40) NOT NULL,
    pay_period_code character varying(40) NOT NULL,
    amount numeric(18,2) NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    is_active boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_salary_items PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_salary_items__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_salary_items__amount_non_negative
        CHECK (amount >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_salary_items__public_id
    ON personnel_file_salary_items (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_salary_items__tenant_file_start_active
    ON personnel_file_salary_items (tenant_id, personnel_file_id, start_date, is_active);

CREATE TABLE IF NOT EXISTS personnel_file_additional_benefits (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    benefit_type_code character varying(80) NOT NULL,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    is_active boolean NOT NULL,
    notes character varying(2000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_additional_benefits PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_additional_benefits__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_additional_benefits__public_id
    ON personnel_file_additional_benefits (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_additional_benefits__tenant_file_type_active
    ON personnel_file_additional_benefits (tenant_id, personnel_file_id, benefit_type_code, is_active);

CREATE TABLE IF NOT EXISTS personnel_file_payment_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    payment_method_code character varying(80) NOT NULL,
    bank_account_public_id uuid,
    is_primary boolean NOT NULL,
    is_active boolean NOT NULL,
    effective_from_utc timestamp with time zone NOT NULL,
    effective_to_utc timestamp with time zone,
    notes character varying(2000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_payment_methods PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_payment_methods__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_payment_methods__effective_dates
        CHECK (effective_to_utc IS NULL OR effective_to_utc >= effective_from_utc)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_payment_methods__public_id
    ON personnel_file_payment_methods (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_payment_methods__tenant_file_active_primary
    ON personnel_file_payment_methods (tenant_id, personnel_file_id, is_active, is_primary);

CREATE TABLE IF NOT EXISTS personnel_file_authorization_substitutions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    substitution_type_code character varying(80) NOT NULL,
    substitute_personnel_file_public_id uuid NOT NULL,
    substitute_position_title character varying(120),
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    is_active boolean NOT NULL,
    notes character varying(2000),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_authorization_substitutions PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_authorization_substitutions__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_authorization_substitutions__dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_authorization_substitutions__public_id
    ON personnel_file_authorization_substitutions (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_authorization_substitutions__tenant_file_type_active
    ON personnel_file_authorization_substitutions (tenant_id, personnel_file_id, substitution_type_code, is_active);

WITH employee_files AS (
    SELECT id,
           public_id,
           tenant_id,
           is_active,
           created_utc
    FROM personnel_files
    WHERE record_type = 'Employee'
), pending AS (
    SELECT file.*
    FROM employee_files file
    WHERE NOT EXISTS (
        SELECT 1
        FROM personnel_file_employee_profiles profile
        WHERE profile.personnel_file_id = file.id
          AND profile.tenant_id = file.tenant_id)
)
INSERT INTO personnel_file_employee_profiles (
    public_id,
    personnel_file_id,
    employee_code,
    normalized_employee_code,
    employment_status_code,
    is_employment_active,
    contract_type_code,
    hire_date,
    contract_start_date,
    contract_end_date,
    vacation_configuration_json,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    gen_random_uuid(),
    pending.id,
    'EMP-' || upper(substr(md5(pending.tenant_id::text || ':' || pending.public_id::text), 1, 10)),
    'EMP-' || upper(substr(md5(pending.tenant_id::text || ':' || pending.public_id::text), 1, 10)),
    CASE WHEN pending.is_active THEN 'ACTIVE' ELSE 'INACTIVE' END,
    pending.is_active,
    'UNSPECIFIED',
    pending.created_utc,
    pending.created_utc,
    NULL,
    NULL,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    pending.tenant_id
FROM pending;

WITH tenant_source AS (
    SELECT DISTINCT public_id AS tenant_id
    FROM companies
), catalog_source AS (
    SELECT * FROM (VALUES
        ('EmployeeStatus', 'ACTIVE', 'Activo', 10),
        ('EmployeeStatus', 'INACTIVE', 'Inactivo', 20),
        ('EmploymentContractType', 'UNSPECIFIED', 'No especificado', 10),
        ('EmploymentWorkday', 'FULL_TIME', 'Tiempo completo', 10),
        ('EmploymentPayrollType', 'MONTHLY', 'Mensual', 10),
        ('EmploymentIncomeType', 'BASE_SALARY', 'Salario base', 10),
        ('EmploymentSalaryRubric', 'ORDINARY', 'Ordinario', 10),
        ('EmploymentPayPeriod', 'MONTHLY', 'Mensual', 10),
        ('EmploymentBenefitType', 'VACATION', 'Vacaciones', 10),
        ('EmploymentPaymentMethod', 'BANK_TRANSFER', 'Transferencia bancaria', 10),
        ('EmploymentAuthorizationSubstitutionType', 'GENERAL', 'General', 10)
    ) AS source(category, code, name, sort_order)
)
INSERT INTO personnel_catalog_items (
    public_id,
    category,
    code,
    normalized_code,
    name,
    normalized_name,
    is_system,
    is_active,
    sort_order,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    gen_random_uuid(),
    catalog.category,
    catalog.code,
    upper(catalog.code),
    catalog.name,
    upper(catalog.name),
    true,
    true,
    catalog.sort_order,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    tenant.tenant_id
FROM tenant_source tenant
CROSS JOIN catalog_source catalog
ON CONFLICT (tenant_id, category, normalized_code) DO UPDATE
SET name = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    is_system = EXCLUDED.is_system,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    modified_utc = EXCLUDED.modified_utc;
