-- HU-023 - Personnel files core

CREATE TABLE IF NOT EXISTS personnel_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    record_type character varying(20) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    full_name character varying(201) NOT NULL,
    normalized_full_name character varying(201) NOT NULL,
    birth_date timestamp with time zone NOT NULL,
    marital_status character varying(80),
    profession character varying(120),
    nationality character varying(120),
    personal_email character varying(320),
    institutional_email character varying(320),
    personal_phone character varying(40),
    institutional_phone character varying(40),
    birth_country character varying(120),
    birth_department character varying(120),
    birth_municipality character varying(120),
    photo_url character varying(1000),
    org_unit_public_id uuid,
    custom_data jsonb,
    is_active boolean NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_files PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_files__public_id
    ON personnel_files (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_files__tenant_name
    ON personnel_files (tenant_id, normalized_full_name);

CREATE INDEX IF NOT EXISTS ix_personnel_files__tenant_type_active
    ON personnel_files (tenant_id, record_type, is_active);

CREATE INDEX IF NOT EXISTS ix_personnel_files__tenant_org_unit
    ON personnel_files (tenant_id, org_unit_public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_files__tenant_birth_date
    ON personnel_files (tenant_id, birth_date);

CREATE TABLE IF NOT EXISTS personnel_file_identifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    identification_type character varying(80) NOT NULL,
    identification_number character varying(80) NOT NULL,
    normalized_identification_number character varying(80) NOT NULL,
    issued_date timestamp with time zone,
    expiry_date timestamp with time zone,
    issuer character varying(200),
    is_primary boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_identifications PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_identifications__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_identifications__issued_expiry
        CHECK (expiry_date IS NULL OR issued_date IS NULL OR expiry_date >= issued_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_identifications__public_id
    ON personnel_file_identifications (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_identifications__tenant_type_number
    ON personnel_file_identifications (tenant_id, identification_type, normalized_identification_number);

CREATE INDEX IF NOT EXISTS ix_personnel_file_identifications__tenant_file
    ON personnel_file_identifications (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    address_line character varying(500) NOT NULL,
    country character varying(120),
    department character varying(120),
    municipality character varying(120),
    postal_code character varying(40),
    is_current boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_addresses PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_addresses__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_addresses__public_id
    ON personnel_file_addresses (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_addresses__tenant_file
    ON personnel_file_addresses (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_emergency_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    name character varying(150) NOT NULL,
    relationship character varying(80) NOT NULL,
    phone character varying(40) NOT NULL,
    address character varying(500),
    workplace character varying(200),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_emergency_contacts PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_emergency_contacts__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_emergency_contacts__public_id
    ON personnel_file_emergency_contacts (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_emergency_contacts__tenant_file
    ON personnel_file_emergency_contacts (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_family_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    full_name character varying(201) NOT NULL,
    relationship character varying(80) NOT NULL,
    nationality character varying(120),
    birth_date timestamp with time zone,
    sex character varying(20) NOT NULL,
    marital_status character varying(80),
    occupation character varying(120),
    document_type character varying(80),
    document_number character varying(80),
    phone character varying(40),
    is_studying boolean NOT NULL,
    study_place character varying(200),
    academic_level character varying(120),
    is_beneficiary boolean NOT NULL,
    is_working boolean NOT NULL,
    workplace character varying(200),
    job_title character varying(120),
    work_phone character varying(40),
    salary numeric(18,2),
    is_deceased boolean NOT NULL,
    deceased_date timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_family_members PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_family_members__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_family_members__deceased_date
        CHECK (is_deceased = FALSE OR deceased_date IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_family_members__public_id
    ON personnel_file_family_members (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_family_members__tenant_file
    ON personnel_file_family_members (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_hobbies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    hobby_name character varying(120) NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_hobbies PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_hobbies__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_hobbies__public_id
    ON personnel_file_hobbies (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_hobbies__tenant_file
    ON personnel_file_hobbies (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_employee_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    related_employee_name character varying(200) NOT NULL,
    relationship character varying(80) NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_employee_relations PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_employee_relations__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_employee_relations__public_id
    ON personnel_file_employee_relations (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_employee_relations__tenant_file
    ON personnel_file_employee_relations (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_bank_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    bank_code character varying(80) NOT NULL,
    currency_code character varying(40) NOT NULL,
    account_number character varying(80) NOT NULL,
    normalized_account_number character varying(80) NOT NULL,
    account_type_code character varying(80) NOT NULL,
    is_primary boolean NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_bank_accounts PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_bank_accounts__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_bank_accounts__public_id
    ON personnel_file_bank_accounts (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_bank_accounts__tenant_file
    ON personnel_file_bank_accounts (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_file_associations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    association_name character varying(200) NOT NULL,
    role character varying(120),
    joined_date timestamp with time zone,
    left_date timestamp with time zone,
    payment numeric(18,2),
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_associations PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_associations__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_personnel_file_associations__joined_left
        CHECK (left_date IS NULL OR joined_date IS NULL OR left_date >= joined_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_associations__public_id
    ON personnel_file_associations (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_associations__tenant_file
    ON personnel_file_associations (tenant_id, personnel_file_id);

CREATE TABLE IF NOT EXISTS personnel_catalog_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    category character varying(80) NOT NULL,
    code character varying(80) NOT NULL,
    normalized_code character varying(80) NOT NULL,
    name character varying(150) NOT NULL,
    normalized_name character varying(150) NOT NULL,
    is_system boolean NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    concurrency_token uuid NOT NULL,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_catalog_items PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_catalog_items__public_id
    ON personnel_catalog_items (public_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_catalog_items__tenant_category_code
    ON personnel_catalog_items (tenant_id, category, normalized_code);

CREATE INDEX IF NOT EXISTS ix_personnel_catalog_items__tenant_category_active_sort
    ON personnel_catalog_items (tenant_id, category, is_active, sort_order);

INSERT INTO rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc
)
VALUES (
    'PERSONNEL_FILES',
    'PERSONNEL_FILES',
    'Personnel Files',
    true,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc'
)
ON CONFLICT (resource_key) DO UPDATE
SET normalized_resource_key = EXCLUDED.normalized_resource_key,
    display_name = EXCLUDED.display_name,
    is_active = EXCLUDED.is_active,
    modified_utc = EXCLUDED.modified_utc;

INSERT INTO plan_entitlements (
    plan_code,
    module_key,
    is_enabled,
    created_utc,
    modified_utc
)
VALUES
    ('FREE', 'PERSONNEL_FILES', true, now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc'),
    ('BASIC', 'PERSONNEL_FILES', true, now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc'),
    ('PRO', 'PERSONNEL_FILES', true, now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc'),
    ('ENTERPRISE', 'PERSONNEL_FILES', true, now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc')
ON CONFLICT (plan_code, module_key) DO UPDATE
SET is_enabled = EXCLUDED.is_enabled,
    modified_utc = EXCLUDED.modified_utc;

WITH tenant_source AS (
    SELECT DISTINCT public_id AS tenant_id
    FROM companies
), catalog_source AS (
    SELECT * FROM (VALUES
        ('MaritalStatus', 'SINGLE', 'Single', 10),
        ('MaritalStatus', 'MARRIED', 'Married', 20),
        ('MaritalStatus', 'DIVORCED', 'Divorced', 30),
        ('Relationship', 'FATHER', 'Father', 10),
        ('Relationship', 'MOTHER', 'Mother', 20),
        ('Relationship', 'SPOUSE', 'Spouse', 30),
        ('Relationship', 'CHILD', 'Child', 40),
        ('IdentificationType', 'DUI', 'Documento Unico de Identidad', 10),
        ('IdentificationType', 'NIT', 'Numero de Identificacion Tributaria', 20),
        ('IdentificationType', 'NUP', 'Numero Unico Previsional', 30),
        ('IdentificationType', 'PASSPORT', 'Passport', 40),
        ('Bank', 'BANCO_AGRICOLA', 'Banco Agricola', 10),
        ('Bank', 'BANCO_CUSCATLAN', 'Banco Cuscatlan', 20),
        ('Currency', 'USD', 'US Dollar', 10),
        ('Currency', 'EUR', 'Euro', 20),
        ('BankAccountType', 'SAVINGS', 'Savings', 10),
        ('BankAccountType', 'CHECKING', 'Checking', 20),
        ('Hobby', 'READING', 'Reading', 10),
        ('Hobby', 'SPORTS', 'Sports', 20),
        ('Association', 'ASSOCIACION_SOLIDARIA', 'Asociacion Solidaria', 10),
        ('Association', 'COOPERATIVA', 'Cooperativa', 20)
    ) AS source(category, code, name, sort_order)
)
INSERT INTO personnel_catalog_items (
    public_id,
    category,
    code,
    normalized_code,
    name,
    normalized_name,
    is_system,
    is_active,
    sort_order,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    gen_random_uuid(),
    catalog.category,
    catalog.code,
    upper(catalog.code),
    catalog.name,
    upper(catalog.name),
    true,
    true,
    catalog.sort_order,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    tenant.tenant_id
FROM tenant_source tenant
CROSS JOIN catalog_source catalog
ON CONFLICT (tenant_id, category, normalized_code) DO UPDATE
SET name = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    is_system = EXCLUDED.is_system,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    modified_utc = EXCLUDED.modified_utc;
