-- HU-030 - Personnel files employee integrations (staging)

CREATE TABLE IF NOT EXISTS personnel_file_performance_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    evaluator_name character varying(200) NOT NULL,
    evaluation_date_utc timestamp with time zone NOT NULL,
    score numeric(18,2),
    qualitative_score_code character varying(80),
    comment character varying(2000),
    source_system character varying(80),
    source_reference character varying(120),
    source_synced_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_performance_evaluations PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_performance_evaluations__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_performance_evaluations__public_id
    ON personnel_file_performance_evaluations (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_performance_evaluations__tenant_file_date
    ON personnel_file_performance_evaluations (tenant_id, personnel_file_id, evaluation_date_utc);

CREATE TABLE IF NOT EXISTS personnel_file_position_competency_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    competency_code character varying(80) NOT NULL,
    desired_behaviors character varying(2000),
    expected_score numeric(18,2),
    achieved_score numeric(18,2),
    gap_score numeric(18,2),
    evaluation_date_utc timestamp with time zone,
    source_system character varying(80),
    source_reference character varying(120),
    source_synced_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_position_competency_results PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_position_competency_results__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_position_competency_results__public_id
    ON personnel_file_position_competency_results (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_position_competency_results__tenant_file_competency
    ON personnel_file_position_competency_results (tenant_id, personnel_file_id, competency_code);

CREATE TABLE IF NOT EXISTS personnel_file_selection_contests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    contest_code character varying(80) NOT NULL,
    contest_name character varying(200) NOT NULL,
    contest_date_utc timestamp with time zone NOT NULL,
    result_code character varying(80) NOT NULL,
    notes character varying(2000),
    source_system character varying(80),
    source_reference character varying(120),
    source_synced_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_selection_contests PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_selection_contests__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_selection_contests__public_id
    ON personnel_file_selection_contests (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_selection_contests__tenant_file_date
    ON personnel_file_selection_contests (tenant_id, personnel_file_id, contest_date_utc);

CREATE TABLE IF NOT EXISTS personnel_file_curricular_competencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    personnel_file_id bigint NOT NULL,
    requirement_type_code character varying(80) NOT NULL,
    requirement_name character varying(200) NOT NULL,
    competency_domain character varying(120) NOT NULL,
    experience_time_value numeric(18,2),
    metric_code character varying(80),
    notes character varying(2000),
    source_system character varying(80),
    source_reference character varying(120),
    source_synced_utc timestamp with time zone,
    created_utc timestamp with time zone NOT NULL,
    modified_utc timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT pk_personnel_file_curricular_competencies PRIMARY KEY (id),
    CONSTRAINT fk_personnel_file_curricular_competencies__personnel_file
        FOREIGN KEY (personnel_file_id)
        REFERENCES personnel_files (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_personnel_file_curricular_competencies__public_id
    ON personnel_file_curricular_competencies (public_id);

CREATE INDEX IF NOT EXISTS ix_personnel_file_curricular_competencies__tenant_file_requirement_type
    ON personnel_file_curricular_competencies (tenant_id, personnel_file_id, requirement_type_code);

WITH tenant_source AS (
    SELECT DISTINCT public_id AS tenant_id
    FROM companies
), catalog_source AS (
    SELECT * FROM (VALUES
        ('EmploymentEvaluationQualitativeScale', 'OUTSTANDING', 'Sobresaliente', 10),
        ('EmploymentEvaluationQualitativeScale', 'EXPECTED', 'Esperado', 20),
        ('EmploymentEvaluationQualitativeScale', 'IMPROVEMENT_REQUIRED', 'Requiere mejora', 30),
        ('EmploymentCurricularRequirementType', 'ACADEMIC', 'Academico', 10),
        ('EmploymentCurricularRequirementType', 'TECHNICAL', 'Tecnico', 20),
        ('EmploymentCurricularMetricType', 'YEARS', 'Anios', 10),
        ('EmploymentCurricularMetricType', 'MONTHS', 'Meses', 20)
    ) AS source(category, code, name, sort_order)
)
INSERT INTO personnel_catalog_items (
    public_id,
    category,
    code,
    normalized_code,
    name,
    normalized_name,
    is_system,
    is_active,
    sort_order,
    concurrency_token,
    created_utc,
    modified_utc,
    tenant_id
)
SELECT
    gen_random_uuid(),
    catalog.category,
    catalog.code,
    upper(catalog.code),
    catalog.name,
    upper(catalog.name),
    true,
    true,
    catalog.sort_order,
    gen_random_uuid(),
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    tenant.tenant_id
FROM tenant_source tenant
CROSS JOIN catalog_source catalog
ON CONFLICT (tenant_id, category, normalized_code) DO UPDATE
SET name = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    is_system = EXCLUDED.is_system,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    modified_utc = EXCLUDED.modified_utc;
