begin;

create table if not exists auth_users
(
    id bigint generated by default as identity,
    public_id uuid not null,
    first_name character varying(100) not null,
    last_name character varying(100) not null,
    email character varying(320) not null,
    normalized_email character varying(320) not null,
    password_hash character varying(512),
    auth_provider character varying(30) not null,
    provider_user_id character varying(200),
    country character varying(100),
    source character varying(100),
    status character varying(30) not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_auth_users primary key (id)
);

create table if not exists companies
(
    id bigint generated by default as identity,
    public_id uuid not null,
    name character varying(150) not null,
    slug character varying(120) not null,
    status character varying(30) not null,
    created_by_user_public_id uuid not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_companies primary key (id)
);

create table if not exists company_subscriptions
(
    id bigint generated by default as identity,
    company_id bigint not null,
    plan_code character varying(40) not null,
    status character varying(30) not null,
    start_date_utc timestamp with time zone not null,
    end_date_utc timestamp with time zone,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_company_subscriptions primary key (id),
    constraint fk_company_subscriptions__companies
        foreign key (company_id) references companies (id) on delete cascade
);

create table if not exists plan_entitlements
(
    id bigint generated by default as identity,
    plan_code character varying(40) not null,
    module_key character varying(60) not null,
    is_enabled boolean not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_plan_entitlements primary key (id)
);

create table if not exists auth_refresh_tokens
(
    id bigint generated by default as identity,
    family_id uuid not null,
    user_id bigint not null,
    token_hash character varying(128) not null,
    expires_utc timestamp with time zone not null,
    revoked_utc timestamp with time zone,
    replaced_by_token_hash character varying(128),
    revocation_reason character varying(100),
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_auth_refresh_tokens primary key (id),
    constraint fk_auth_refresh_tokens__auth_users
        foreign key (user_id) references auth_users (id) on delete cascade
);

create table if not exists iam_permissions
(
    id bigint generated by default as identity,
    public_id uuid not null,
    tenant_id uuid not null,
    code character varying(200) not null,
    normalized_code character varying(200) not null,
    name character varying(120) not null,
    description character varying(500),
    module character varying(100) not null,
    normalized_module character varying(100) not null,
    screen character varying(100) not null,
    normalized_screen character varying(100) not null,
    kind character varying(30) not null,
    action character varying(100),
    normalized_action character varying(100),
    field_name character varying(100),
    normalized_field_name character varying(100),
    field_access character varying(20),
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_iam_permissions primary key (id)
);

create table if not exists iam_roles
(
    id bigint generated by default as identity,
    public_id uuid not null,
    tenant_id uuid not null,
    name character varying(100) not null,
    normalized_name character varying(100) not null,
    description character varying(500),
    is_system_role boolean not null default false,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_iam_roles primary key (id)
);

create table if not exists user_companies
(
    id bigint generated by default as identity,
    user_id bigint not null,
    company_id bigint not null,
    role_id bigint not null,
    is_primary boolean not null,
    status character varying(30) not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_user_companies primary key (id),
    constraint fk_user_companies__auth_users
        foreign key (user_id) references auth_users (id) on delete cascade,
    constraint fk_user_companies__companies
        foreign key (company_id) references companies (id) on delete cascade,
    constraint fk_user_companies__iam_roles
        foreign key (role_id) references iam_roles (id) on delete restrict
);

create table if not exists company_invitation_tokens
(
    id bigint generated by default as identity,
    user_id bigint not null,
    company_id bigint not null,
    token_hash character varying(128) not null,
    expiration_utc timestamp with time zone not null,
    is_used boolean not null default false,
    revoked_utc timestamp with time zone,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_company_invitation_tokens primary key (id),
    constraint fk_company_invitation_tokens__auth_users
        foreign key (user_id) references auth_users (id) on delete cascade,
    constraint fk_company_invitation_tokens__companies
        foreign key (company_id) references companies (id) on delete cascade
);

create table if not exists iam_users
(
    id bigint generated by default as identity,
    public_id uuid not null,
    tenant_id uuid not null,
    first_name character varying(100) not null,
    last_name character varying(100) not null,
    email character varying(320) not null,
    normalized_email character varying(320) not null,
    is_active boolean not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_iam_users primary key (id)
);

create table if not exists iam_role_permission_assignments
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_id bigint not null,
    permission_id bigint not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_iam_role_permission_assignments primary key (id),
    constraint fk_iam_role_perm__iam_roles__role_id
        foreign key (role_id) references iam_roles (id) on delete cascade,
    constraint fk_iam_role_perm__iam_permissions__permission_id
        foreign key (permission_id) references iam_permissions (id) on delete cascade
);

create table if not exists iam_user_role_assignments
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    user_id bigint not null,
    role_id bigint not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_iam_user_role_assignments primary key (id),
    constraint fk_iam_user_role__iam_users__user_id
        foreign key (user_id) references iam_users (id) on delete cascade,
    constraint fk_iam_user_role__iam_roles__role_id
        foreign key (role_id) references iam_roles (id) on delete cascade
);

create table if not exists rbac_resource_catalog
(
    resource_key character varying(100) not null,
    normalized_resource_key character varying(100) not null,
    display_name character varying(120) not null,
    is_active boolean not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_rbac_resource_catalog primary key (resource_key)
);

create table if not exists rbac_permission_audit_logs
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_public_id uuid not null,
    resource_key character varying(100) not null,
    normalized_resource_key character varying(100) not null,
    changed_by_user_id uuid not null,
    change_type character varying(20) not null,
    before_json jsonb not null,
    after_json jsonb not null,
    changed_at_utc timestamp with time zone not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_rbac_permission_audit_logs primary key (id)
);

create table if not exists field_catalog
(
    id bigint generated by default as identity,
    field_key character varying(150) not null,
    normalized_field_key character varying(150) not null,
    resource_key character varying(100) not null,
    normalized_resource_key character varying(100) not null,
    property_name character varying(100) not null,
    normalized_property_name character varying(100) not null,
    display_name character varying(120) not null,
    is_configurable boolean not null,
    is_sensitive boolean not null,
    data_type character varying(40) not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_field_catalog primary key (id)
);

create table if not exists role_field_permissions
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_id bigint not null,
    field_key character varying(150) not null,
    normalized_field_key character varying(150) not null,
    is_visible boolean not null,
    is_editable boolean not null,
    is_required boolean not null,
    is_masked boolean not null,
    updated_by_user_id uuid not null,
    updated_at_utc timestamp with time zone not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_role_field_permissions primary key (id),
    constraint fk_role_field_permissions__iam_roles__role_id
        foreign key (role_id) references iam_roles (id) on delete cascade
);

create table if not exists field_permission_audit_logs
(
    id bigint generated by default as identity,
    tenant_id uuid not null,
    role_public_id uuid not null,
    field_key character varying(150) not null,
    normalized_field_key character varying(150) not null,
    changed_by_user_id uuid not null,
    before_json jsonb,
    after_json jsonb not null,
    changed_at_utc timestamp with time zone not null,
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_field_permission_audit_logs primary key (id)
);

create unique index if not exists uq_auth_users__public_id
    on auth_users (public_id);

create unique index if not exists uq_companies__public_id
    on companies (public_id);

create unique index if not exists uq_companies__slug
    on companies (slug);

create unique index if not exists uq_company_subscriptions__company_active
    on company_subscriptions (company_id, status)
    where status = 'Active';

create unique index if not exists uq_plan_entitlements__plan_module
    on plan_entitlements (plan_code, module_key);

create unique index if not exists uq_auth_users__normalized_email
    on auth_users (normalized_email);

create unique index if not exists uq_auth_users__provider_link
    on auth_users (auth_provider, provider_user_id)
    where provider_user_id is not null;

create unique index if not exists uq_auth_refresh_tokens__token_hash
    on auth_refresh_tokens (token_hash);

create index if not exists ix_auth_refresh_tokens__family_user
    on auth_refresh_tokens (family_id, user_id);

create unique index if not exists uq_iam_permissions__tenant_code
    on iam_permissions (tenant_id, normalized_code);

create index if not exists ix_iam_permissions__tenant_screen
    on iam_permissions (tenant_id, normalized_module, normalized_screen);

create unique index if not exists uq_iam_roles__tenant_name
    on iam_roles (tenant_id, normalized_name);

create index if not exists ix_iam_roles__tenant_name
    on iam_roles (tenant_id, name);

create unique index if not exists uq_iam_users__tenant_email
    on iam_users (tenant_id, normalized_email);

create index if not exists ix_iam_users__tenant_name
    on iam_users (tenant_id, last_name, first_name);

create unique index if not exists uq_iam_role_perm__tenant_role_perm
    on iam_role_permission_assignments (tenant_id, role_id, permission_id);

create unique index if not exists uq_iam_user_role__tenant_user_role
    on iam_user_role_assignments (tenant_id, user_id, role_id);

create unique index if not exists uq_rbac_resource_catalog__normalized_resource_key
    on rbac_resource_catalog (normalized_resource_key);

create index if not exists ix_rbac_permission_audit_logs__tenant_role_changed_at
    on rbac_permission_audit_logs (tenant_id, role_public_id, changed_at_utc);

create index if not exists ix_rbac_permission_audit_logs__tenant_resource_changed_at
    on rbac_permission_audit_logs (tenant_id, normalized_resource_key, changed_at_utc);

create unique index if not exists uq_field_catalog__normalized_field_key
    on field_catalog (normalized_field_key);

create index if not exists ix_field_catalog__resource_configurable
    on field_catalog (normalized_resource_key, is_configurable);

create unique index if not exists uq_role_field_permissions__tenant_role_field
    on role_field_permissions (tenant_id, role_id, normalized_field_key);

create index if not exists ix_role_field_permissions__tenant_role
    on role_field_permissions (tenant_id, role_id);

create index if not exists ix_field_permission_audit_logs__tenant_role_changed_at
    on field_permission_audit_logs (tenant_id, role_public_id, changed_at_utc);

create index if not exists ix_field_permission_audit_logs__tenant_field_changed_at
    on field_permission_audit_logs (tenant_id, normalized_field_key, changed_at_utc);

create unique index if not exists uq_user_companies__primary_user
    on user_companies (user_id)
    where is_primary = true;

create unique index if not exists uq_user_companies__user_company
    on user_companies (user_id, company_id);

create index if not exists ix_user_companies__company_status_role
    on user_companies (company_id, status, role_id);

create unique index if not exists uq_company_invitation_tokens__token_hash
    on company_invitation_tokens (token_hash);

create index if not exists ix_company_invitation_tokens__user_company
    on company_invitation_tokens (user_id, company_id);

insert into rbac_resource_catalog (
    resource_key,
    normalized_resource_key,
    display_name,
    is_active,
    created_utc,
    modified_utc)
values
    ('RBAC_USERS', 'RBAC_USERS', 'Users', true, now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_ROLES', 'RBAC_ROLES', 'Roles', true, now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_PERMISSIONS', 'RBAC_PERMISSIONS', 'Permissions', true, now() at time zone 'utc', now() at time zone 'utc')
on conflict (resource_key) do update
set normalized_resource_key = excluded.normalized_resource_key,
    display_name = excluded.display_name,
    is_active = excluded.is_active,
    modified_utc = excluded.modified_utc;

insert into field_catalog (
    field_key,
    normalized_field_key,
    resource_key,
    normalized_resource_key,
    property_name,
    normalized_property_name,
    display_name,
    is_configurable,
    is_sensitive,
    data_type,
    created_utc,
    modified_utc)
values
    ('RBAC_USERS.ID', 'RBAC_USERS.ID', 'RBAC_USERS', 'RBAC_USERS', 'Id', 'ID', 'Internal Id', false, false, 'guid', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.EMAIL', 'RBAC_USERS.EMAIL', 'RBAC_USERS', 'RBAC_USERS', 'Email', 'EMAIL', 'Email', true, true, 'string', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.FIRST_NAME', 'RBAC_USERS.FIRST_NAME', 'RBAC_USERS', 'RBAC_USERS', 'FirstName', 'FIRSTNAME', 'First Name', true, false, 'string', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.LAST_NAME', 'RBAC_USERS.LAST_NAME', 'RBAC_USERS', 'RBAC_USERS', 'LastName', 'LASTNAME', 'Last Name', true, false, 'string', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.ROLE', 'RBAC_USERS.ROLE', 'RBAC_USERS', 'RBAC_USERS', 'Role', 'ROLE', 'Role', true, false, 'lookup', now() at time zone 'utc', now() at time zone 'utc'),
    ('RBAC_USERS.STATUS', 'RBAC_USERS.STATUS', 'RBAC_USERS', 'RBAC_USERS', 'Status', 'STATUS', 'Status', true, false, 'enum', now() at time zone 'utc', now() at time zone 'utc')
on conflict (normalized_field_key) do update
set resource_key = excluded.resource_key,
    normalized_resource_key = excluded.normalized_resource_key,
    property_name = excluded.property_name,
    normalized_property_name = excluded.normalized_property_name,
    display_name = excluded.display_name,
    is_configurable = excluded.is_configurable,
    is_sensitive = excluded.is_sensitive,
    data_type = excluded.data_type,
    modified_utc = excluded.modified_utc;

commit;
