begin;

create table if not exists auth_refresh_tokens
(
    id bigint generated by default as identity,
    family_id uuid not null,
    user_id bigint not null,
    token_hash character varying(128) not null,
    expires_utc timestamp with time zone not null,
    revoked_utc timestamp with time zone,
    replaced_by_token_hash character varying(128),
    revocation_reason character varying(100),
    created_utc timestamp with time zone not null,
    modified_utc timestamp with time zone,
    constraint pk_auth_refresh_tokens primary key (id),
    constraint fk_auth_refresh_tokens__auth_users
        foreign key (user_id) references auth_users (id) on delete cascade
);

create unique index if not exists uq_auth_refresh_tokens__token_hash
    on auth_refresh_tokens (token_hash);

create index if not exists ix_auth_refresh_tokens__family_user
    on auth_refresh_tokens (family_id, user_id);

update auth_users
set email = lower(trim(email)),
    normalized_email = lower(trim(email))
where email <> lower(trim(email))
   or normalized_email <> lower(trim(email));

commit;
