namespace CLARIHR.Domain.Locations;

internal static class CountryCatalogData
{
    public static IReadOnlyList<CountryCatalogDefinition> Items { get; } =
    [
        new CountryCatalogDefinition(-7000L, "AF", "Afghanistan", 1),
        new CountryCatalogDefinition(-7001L, "AX", "Aland Islands", 2),
        new CountryCatalogDefinition(-7002L, "AL", "Albania", 3),
        new CountryCatalogDefinition(-7003L, "DZ", "Algeria", 4),
        new CountryCatalogDefinition(-7004L, "AS", "American Samoa", 5),
        new CountryCatalogDefinition(-7005L, "AD", "Andorra", 6),
        new CountryCatalogDefinition(-7006L, "AO", "Angola", 7),
        new CountryCatalogDefinition(-7007L, "AI", "Anguilla", 8),
        new CountryCatalogDefinition(-7008L, "AG", "Antigua & Barbuda", 9),
        new CountryCatalogDefinition(-7009L, "AR", "Argentina", 10),
        new CountryCatalogDefinition(-7010L, "AM", "Armenia", 11),
        new CountryCatalogDefinition(-7011L, "AW", "Aruba", 12),
        new CountryCatalogDefinition(-7012L, "AU", "Australia", 13),
        new CountryCatalogDefinition(-7013L, "AT", "Austria", 14),
        new CountryCatalogDefinition(-7014L, "AZ", "Azerbaijan", 15),
        new CountryCatalogDefinition(-7015L, "BS", "Bahamas", 16),
        new CountryCatalogDefinition(-7016L, "BH", "Bahrain", 17),
        new CountryCatalogDefinition(-7017L, "BD", "Bangladesh", 18),
        new CountryCatalogDefinition(-7018L, "BB", "Barbados", 19),
        new CountryCatalogDefinition(-7019L, "BY", "Belarus", 20),
        new CountryCatalogDefinition(-7020L, "BE", "Belgium", 21),
        new CountryCatalogDefinition(-7021L, "BZ", "Belize", 22),
        new CountryCatalogDefinition(-7022L, "BJ", "Benin", 23),
        new CountryCatalogDefinition(-7023L, "BM", "Bermuda", 24),
        new CountryCatalogDefinition(-7024L, "BT", "Bhutan", 25),
        new CountryCatalogDefinition(-7025L, "BO", "Bolivia", 26),
        new CountryCatalogDefinition(-7026L, "BA", "Bosnia & Herzegovina", 27),
        new CountryCatalogDefinition(-7027L, "BW", "Botswana", 28),
        new CountryCatalogDefinition(-7028L, "BR", "Brazil", 29),
        new CountryCatalogDefinition(-7029L, "VG", "British Virgin Islands", 30),
        new CountryCatalogDefinition(-7030L, "BN", "Brunei", 31),
        new CountryCatalogDefinition(-7031L, "BG", "Bulgaria", 32),
        new CountryCatalogDefinition(-7032L, "BF", "Burkina Faso", 33),
        new CountryCatalogDefinition(-7033L, "BI", "Burundi", 34),
        new CountryCatalogDefinition(-7034L, "KH", "Cambodia", 35),
        new CountryCatalogDefinition(-7035L, "CM", "Cameroon", 36),
        new CountryCatalogDefinition(-7036L, "CA", "Canada", 37),
        new CountryCatalogDefinition(-7037L, "IC", "Canary Islands", 38),
        new CountryCatalogDefinition(-7038L, "CV", "Cape Verde", 39),
        new CountryCatalogDefinition(-7039L, "BQ", "Caribbean Netherlands", 40),
        new CountryCatalogDefinition(-7040L, "KY", "Cayman Islands", 41),
        new CountryCatalogDefinition(-7041L, "CF", "Central African Republic", 42),
        new CountryCatalogDefinition(-7042L, "EA", "Ceuta & Melilla", 43),
        new CountryCatalogDefinition(-7043L, "TD", "Chad", 44),
        new CountryCatalogDefinition(-7044L, "IO", "Chagos Archipelago", 45),
        new CountryCatalogDefinition(-7045L, "CL", "Chile", 46),
        new CountryCatalogDefinition(-7046L, "CN", "China mainland", 47),
        new CountryCatalogDefinition(-7047L, "CX", "Christmas Island", 48),
        new CountryCatalogDefinition(-7048L, "CC", "Cocos (Keeling) Islands", 49),
        new CountryCatalogDefinition(-7049L, "CO", "Colombia", 50),
        new CountryCatalogDefinition(-7050L, "KM", "Comoros", 51),
        new CountryCatalogDefinition(-7051L, "CG", "Congo - Brazzaville", 52),
        new CountryCatalogDefinition(-7052L, "CD", "Congo - Kinshasa", 53),
        new CountryCatalogDefinition(-7053L, "CK", "Cook Islands", 54),
        new CountryCatalogDefinition(-7054L, "CR", "Costa Rica", 55),
        new CountryCatalogDefinition(-7055L, "CI", "Cote d'Ivoire", 56),
        new CountryCatalogDefinition(-7056L, "HR", "Croatia", 57),
        new CountryCatalogDefinition(-7057L, "CU", "Cuba", 58),
        new CountryCatalogDefinition(-7058L, "CW", "Curacao", 59),
        new CountryCatalogDefinition(-7059L, "CY", "Cyprus", 60),
        new CountryCatalogDefinition(-7060L, "CZ", "Czechia", 61),
        new CountryCatalogDefinition(-7061L, "DK", "Denmark", 62),
        new CountryCatalogDefinition(-7062L, "DG", "Diego Garcia", 63),
        new CountryCatalogDefinition(-7063L, "DJ", "Djibouti", 64),
        new CountryCatalogDefinition(-7064L, "DM", "Dominica", 65),
        new CountryCatalogDefinition(-7065L, "DO", "Dominican Republic", 66),
        new CountryCatalogDefinition(-7066L, "EC", "Ecuador", 67),
        new CountryCatalogDefinition(-7067L, "EG", "Egypt", 68),
        new CountryCatalogDefinition(-7068L, "SV", "El Salvador", 69),
        new CountryCatalogDefinition(-7069L, "GQ", "Equatorial Guinea", 70),
        new CountryCatalogDefinition(-7070L, "ER", "Eritrea", 71),
        new CountryCatalogDefinition(-7071L, "EE", "Estonia", 72),
        new CountryCatalogDefinition(-7072L, "SZ", "Eswatini", 73),
        new CountryCatalogDefinition(-7073L, "ET", "Ethiopia", 74),
        new CountryCatalogDefinition(-7074L, "FK", "Falkland Islands", 75),
        new CountryCatalogDefinition(-7075L, "FO", "Faroe Islands", 76),
        new CountryCatalogDefinition(-7076L, "FJ", "Fiji", 77),
        new CountryCatalogDefinition(-7077L, "FI", "Finland", 78),
        new CountryCatalogDefinition(-7078L, "FR", "France", 79),
        new CountryCatalogDefinition(-7079L, "GF", "French Guiana", 80),
        new CountryCatalogDefinition(-7080L, "PF", "French Polynesia", 81),
        new CountryCatalogDefinition(-7081L, "GA", "Gabon", 82),
        new CountryCatalogDefinition(-7082L, "GM", "Gambia", 83),
        new CountryCatalogDefinition(-7083L, "GE", "Georgia", 84),
        new CountryCatalogDefinition(-7084L, "DE", "Germany", 85),
        new CountryCatalogDefinition(-7085L, "GH", "Ghana", 86),
        new CountryCatalogDefinition(-7086L, "GI", "Gibraltar", 87),
        new CountryCatalogDefinition(-7087L, "GR", "Greece", 88),
        new CountryCatalogDefinition(-7088L, "GL", "Greenland", 89),
        new CountryCatalogDefinition(-7089L, "GD", "Grenada", 90),
        new CountryCatalogDefinition(-7090L, "GP", "Guadeloupe", 91),
        new CountryCatalogDefinition(-7091L, "GU", "Guam", 92),
        new CountryCatalogDefinition(-7092L, "GT", "Guatemala", 93),
        new CountryCatalogDefinition(-7093L, "GG", "Guernsey", 94),
        new CountryCatalogDefinition(-7094L, "GN", "Guinea", 95),
        new CountryCatalogDefinition(-7095L, "GW", "Guinea-Bissau", 96),
        new CountryCatalogDefinition(-7096L, "GY", "Guyana", 97),
        new CountryCatalogDefinition(-7097L, "HT", "Haiti", 98),
        new CountryCatalogDefinition(-7098L, "HN", "Honduras", 99),
        new CountryCatalogDefinition(-7099L, "HK", "Hong Kong", 100),
        new CountryCatalogDefinition(-7100L, "HU", "Hungary", 101),
        new CountryCatalogDefinition(-7101L, "IS", "Iceland", 102),
        new CountryCatalogDefinition(-7102L, "IN", "India", 103),
        new CountryCatalogDefinition(-7103L, "ID", "Indonesia", 104),
        new CountryCatalogDefinition(-7104L, "IR", "Iran", 105),
        new CountryCatalogDefinition(-7105L, "IQ", "Iraq", 106),
        new CountryCatalogDefinition(-7106L, "IE", "Ireland", 107),
        new CountryCatalogDefinition(-7107L, "IM", "Isle of Man", 108),
        new CountryCatalogDefinition(-7108L, "IL", "Israel", 109),
        new CountryCatalogDefinition(-7109L, "IT", "Italy", 110),
        new CountryCatalogDefinition(-7110L, "JM", "Jamaica", 111),
        new CountryCatalogDefinition(-7111L, "JP", "Japan", 112),
        new CountryCatalogDefinition(-7112L, "JE", "Jersey", 113),
        new CountryCatalogDefinition(-7113L, "JO", "Jordan", 114),
        new CountryCatalogDefinition(-7114L, "KZ", "Kazakhstan", 115),
        new CountryCatalogDefinition(-7115L, "KE", "Kenya", 116),
        new CountryCatalogDefinition(-7116L, "KI", "Kiribati", 117),
        new CountryCatalogDefinition(-7117L, "XK", "Kosovo", 118),
        new CountryCatalogDefinition(-7118L, "KW", "Kuwait", 119),
        new CountryCatalogDefinition(-7119L, "KG", "Kyrgyzstan", 120),
        new CountryCatalogDefinition(-7120L, "LA", "Laos", 121),
        new CountryCatalogDefinition(-7121L, "LV", "Latvia", 122),
        new CountryCatalogDefinition(-7122L, "LB", "Lebanon", 123),
        new CountryCatalogDefinition(-7123L, "LS", "Lesotho", 124),
        new CountryCatalogDefinition(-7124L, "LR", "Liberia", 125),
        new CountryCatalogDefinition(-7125L, "LY", "Libya", 126),
        new CountryCatalogDefinition(-7126L, "LI", "Liechtenstein", 127),
        new CountryCatalogDefinition(-7127L, "LT", "Lithuania", 128),
        new CountryCatalogDefinition(-7128L, "LU", "Luxembourg", 129),
        new CountryCatalogDefinition(-7129L, "MO", "Macao", 130),
        new CountryCatalogDefinition(-7130L, "MG", "Madagascar", 131),
        new CountryCatalogDefinition(-7131L, "MW", "Malawi", 132),
        new CountryCatalogDefinition(-7132L, "MY", "Malaysia", 133),
        new CountryCatalogDefinition(-7133L, "MV", "Maldives", 134),
        new CountryCatalogDefinition(-7134L, "ML", "Mali", 135),
        new CountryCatalogDefinition(-7135L, "MT", "Malta", 136),
        new CountryCatalogDefinition(-7136L, "MH", "Marshall Islands", 137),
        new CountryCatalogDefinition(-7137L, "MQ", "Martinique", 138),
        new CountryCatalogDefinition(-7138L, "MR", "Mauritania", 139),
        new CountryCatalogDefinition(-7139L, "MU", "Mauritius", 140),
        new CountryCatalogDefinition(-7140L, "YT", "Mayotte", 141),
        new CountryCatalogDefinition(-7141L, "MX", "Mexico", 142),
        new CountryCatalogDefinition(-7142L, "FM", "Micronesia", 143),
        new CountryCatalogDefinition(-7143L, "MD", "Moldova", 144),
        new CountryCatalogDefinition(-7144L, "MC", "Monaco", 145),
        new CountryCatalogDefinition(-7145L, "MN", "Mongolia", 146),
        new CountryCatalogDefinition(-7146L, "ME", "Montenegro", 147),
        new CountryCatalogDefinition(-7147L, "MS", "Montserrat", 148),
        new CountryCatalogDefinition(-7148L, "MA", "Morocco", 149),
        new CountryCatalogDefinition(-7149L, "MZ", "Mozambique", 150),
        new CountryCatalogDefinition(-7150L, "MM", "Myanmar (Burma)", 151),
        new CountryCatalogDefinition(-7151L, "NA", "Namibia", 152),
        new CountryCatalogDefinition(-7152L, "NR", "Nauru", 153),
        new CountryCatalogDefinition(-7153L, "NP", "Nepal", 154),
        new CountryCatalogDefinition(-7154L, "NL", "Netherlands", 155),
        new CountryCatalogDefinition(-7155L, "NC", "New Caledonia", 156),
        new CountryCatalogDefinition(-7156L, "NZ", "New Zealand", 157),
        new CountryCatalogDefinition(-7157L, "NI", "Nicaragua", 158),
        new CountryCatalogDefinition(-7158L, "NE", "Niger", 159),
        new CountryCatalogDefinition(-7159L, "NG", "Nigeria", 160),
        new CountryCatalogDefinition(-7160L, "NU", "Niue", 161),
        new CountryCatalogDefinition(-7161L, "NF", "Norfolk Island", 162),
        new CountryCatalogDefinition(-7162L, "KP", "North Korea", 163),
        new CountryCatalogDefinition(-7163L, "MK", "North Macedonia", 164),
        new CountryCatalogDefinition(-7164L, "MP", "Northern Mariana Islands", 165),
        new CountryCatalogDefinition(-7165L, "NO", "Norway", 166),
        new CountryCatalogDefinition(-7166L, "OM", "Oman", 167),
        new CountryCatalogDefinition(-7167L, "PK", "Pakistan", 168),
        new CountryCatalogDefinition(-7168L, "PW", "Palau", 169),
        new CountryCatalogDefinition(-7169L, "PS", "Palestinian Territories", 170),
        new CountryCatalogDefinition(-7170L, "PA", "Panama", 171),
        new CountryCatalogDefinition(-7171L, "PG", "Papua New Guinea", 172),
        new CountryCatalogDefinition(-7172L, "PY", "Paraguay", 173),
        new CountryCatalogDefinition(-7173L, "PE", "Peru", 174),
        new CountryCatalogDefinition(-7174L, "PH", "Philippines", 175),
        new CountryCatalogDefinition(-7175L, "PN", "Pitcairn Islands", 176),
        new CountryCatalogDefinition(-7176L, "PL", "Poland", 177),
        new CountryCatalogDefinition(-7177L, "PT", "Portugal", 178),
        new CountryCatalogDefinition(-7178L, "PR", "Puerto Rico", 179),
        new CountryCatalogDefinition(-7179L, "QA", "Qatar", 180),
        new CountryCatalogDefinition(-7180L, "RE", "Reunion", 181),
        new CountryCatalogDefinition(-7181L, "RO", "Romania", 182),
        new CountryCatalogDefinition(-7182L, "RU", "Russia", 183),
        new CountryCatalogDefinition(-7183L, "RW", "Rwanda", 184),
        new CountryCatalogDefinition(-7184L, "WS", "Samoa", 185),
        new CountryCatalogDefinition(-7185L, "SM", "San Marino", 186),
        new CountryCatalogDefinition(-7186L, "ST", "Sao Tome & Principe", 187),
        new CountryCatalogDefinition(-7187L, "SA", "Saudi Arabia", 188),
        new CountryCatalogDefinition(-7188L, "SN", "Senegal", 189),
        new CountryCatalogDefinition(-7189L, "RS", "Serbia", 190),
        new CountryCatalogDefinition(-7190L, "SC", "Seychelles", 191),
        new CountryCatalogDefinition(-7191L, "SL", "Sierra Leone", 192),
        new CountryCatalogDefinition(-7192L, "SG", "Singapore", 193),
        new CountryCatalogDefinition(-7193L, "SX", "Sint Maarten", 194),
        new CountryCatalogDefinition(-7194L, "SK", "Slovakia", 195),
        new CountryCatalogDefinition(-7195L, "SI", "Slovenia", 196),
        new CountryCatalogDefinition(-7196L, "SB", "Solomon Islands", 197),
        new CountryCatalogDefinition(-7197L, "SO", "Somalia", 198),
        new CountryCatalogDefinition(-7198L, "ZA", "South Africa", 199),
        new CountryCatalogDefinition(-7199L, "KR", "South Korea", 200),
        new CountryCatalogDefinition(-7200L, "SS", "South Sudan", 201),
        new CountryCatalogDefinition(-7201L, "ES", "Spain", 202),
        new CountryCatalogDefinition(-7202L, "LK", "Sri Lanka", 203),
        new CountryCatalogDefinition(-7203L, "BL", "St. Barthelemy", 204),
        new CountryCatalogDefinition(-7204L, "SH", "St. Helena", 205),
        new CountryCatalogDefinition(-7205L, "KN", "St. Kitts & Nevis", 206),
        new CountryCatalogDefinition(-7206L, "LC", "St. Lucia", 207),
        new CountryCatalogDefinition(-7207L, "MF", "St. Martin", 208),
        new CountryCatalogDefinition(-7208L, "PM", "St. Pierre & Miquelon", 209),
        new CountryCatalogDefinition(-7209L, "VC", "St. Vincent & Grenadines", 210),
        new CountryCatalogDefinition(-7210L, "SD", "Sudan", 211),
        new CountryCatalogDefinition(-7211L, "SR", "Suriname", 212),
        new CountryCatalogDefinition(-7212L, "SJ", "Svalbard & Jan Mayen", 213),
        new CountryCatalogDefinition(-7213L, "SE", "Sweden", 214),
        new CountryCatalogDefinition(-7214L, "CH", "Switzerland", 215),
        new CountryCatalogDefinition(-7215L, "SY", "Syria", 216),
        new CountryCatalogDefinition(-7216L, "TW", "Taiwan", 217),
        new CountryCatalogDefinition(-7217L, "TJ", "Tajikistan", 218),
        new CountryCatalogDefinition(-7218L, "TZ", "Tanzania", 219),
        new CountryCatalogDefinition(-7219L, "TH", "Thailand", 220),
        new CountryCatalogDefinition(-7220L, "TL", "Timor-Leste", 221),
        new CountryCatalogDefinition(-7221L, "TG", "Togo", 222),
        new CountryCatalogDefinition(-7222L, "TK", "Tokelau", 223),
        new CountryCatalogDefinition(-7223L, "TO", "Tonga", 224),
        new CountryCatalogDefinition(-7224L, "TT", "Trinidad & Tobago", 225),
        new CountryCatalogDefinition(-7225L, "TN", "Tunisia", 226),
        new CountryCatalogDefinition(-7226L, "TR", "Turkiye", 227),
        new CountryCatalogDefinition(-7227L, "TM", "Turkmenistan", 228),
        new CountryCatalogDefinition(-7228L, "TC", "Turks & Caicos Islands", 229),
        new CountryCatalogDefinition(-7229L, "TV", "Tuvalu", 230),
        new CountryCatalogDefinition(-7230L, "UM", "U.S. Outlying Islands", 231),
        new CountryCatalogDefinition(-7231L, "VI", "U.S. Virgin Islands", 232),
        new CountryCatalogDefinition(-7232L, "UG", "Uganda", 233),
        new CountryCatalogDefinition(-7233L, "UA", "Ukraine", 234),
        new CountryCatalogDefinition(-7234L, "AE", "United Arab Emirates", 235),
        new CountryCatalogDefinition(-7235L, "GB", "United Kingdom", 236),
        new CountryCatalogDefinition(-7236L, "US", "United States", 237),
        new CountryCatalogDefinition(-7237L, "UY", "Uruguay", 238),
        new CountryCatalogDefinition(-7238L, "UZ", "Uzbekistan", 239),
        new CountryCatalogDefinition(-7239L, "VU", "Vanuatu", 240),
        new CountryCatalogDefinition(-7240L, "VA", "Vatican City", 241),
        new CountryCatalogDefinition(-7241L, "VE", "Venezuela", 242),
        new CountryCatalogDefinition(-7242L, "VN", "Vietnam", 243),
        new CountryCatalogDefinition(-7243L, "WF", "Wallis & Futuna", 244),
        new CountryCatalogDefinition(-7244L, "EH", "Western Sahara", 245),
        new CountryCatalogDefinition(-7245L, "YE", "Yemen", 246),
        new CountryCatalogDefinition(-7246L, "ZM", "Zambia", 247),
        new CountryCatalogDefinition(-7247L, "ZW", "Zimbabwe", 248)
    ];
}
