using CLARIHR.Application.Abstractions.Auth;
using CLARIHR.Application.Abstractions.Auditing;
using CLARIHR.Application.Abstractions.Authentication;
using CLARIHR.Application.Abstractions.Banks;
using CLARIHR.Application.Abstractions.Companies;
using CLARIHR.Application.Abstractions.CompetencyFramework;
using CLARIHR.Application.Abstractions.CostCenters;
using CLARIHR.Application.Abstractions.IdentityAccess;
using CLARIHR.Application.Abstractions.InternalCatalogs;
using CLARIHR.Application.Abstractions.JobProfiles;
using CLARIHR.Application.Abstractions.LegalRepresentatives;
using CLARIHR.Application.Abstractions.Localization;
using CLARIHR.Application.Abstractions.Locations;
using CLARIHR.Application.Abstractions.OrgUnits;
using CLARIHR.Application.Abstractions.OrgStructureCatalogs;
using CLARIHR.Application.Abstractions.EducationCatalogs;
using CLARIHR.Application.Abstractions.DocumentTypeCatalogs;
using CLARIHR.Application.Abstractions.PersonnelFiles;
using CLARIHR.Application.Abstractions.Platform;
using CLARIHR.Application.Abstractions.PositionDescriptionCatalogs;
using CLARIHR.Application.Abstractions.PositionSlots;
using CLARIHR.Application.Abstractions.Persistence;
using CLARIHR.Application.Abstractions.Policies;
using CLARIHR.Application.Abstractions.Preferences;
using CLARIHR.Application.Abstractions.Reports;
using CLARIHR.Application.Abstractions.Reports.Documents;
using CLARIHR.Application.Abstractions.SalaryTabulator;
using CLARIHR.Application.Features.JobProfiles;
using CLARIHR.Application.Abstractions.SystemCatalogs;
using CLARIHR.Application.Abstractions.Tenancy;
using CLARIHR.Application.Abstractions.Time;
using CLARIHR.Infrastructure.Auth;
using CLARIHR.Infrastructure.Auditing;
using CLARIHR.Infrastructure.Authentication;
using CLARIHR.Infrastructure.Banks;
using CLARIHR.Infrastructure.Companies;
using CLARIHR.Infrastructure.CompetencyFramework;
using CLARIHR.Infrastructure.Configuration;
using CLARIHR.Infrastructure.CostCenters;
using CLARIHR.Infrastructure.IdentityAccess;
using CLARIHR.Infrastructure.InternalCatalogs;
using CLARIHR.Infrastructure.JobProfiles;
using CLARIHR.Infrastructure.LegalRepresentatives;
using CLARIHR.Infrastructure.Localization;
using CLARIHR.Infrastructure.Locations;
using CLARIHR.Infrastructure.OrgUnits;
using CLARIHR.Infrastructure.OrgStructureCatalogs;
using CLARIHR.Infrastructure.EducationCatalogs;
using CLARIHR.Infrastructure.Files.Azure;
using CLARIHR.Infrastructure.Files.Configuration;
using CLARIHR.Infrastructure.Files;
using CLARIHR.Infrastructure.Files.BackgroundJobs;
using CLARIHR.Application.Abstractions.Files;
using CLARIHR.Infrastructure.PersonnelFiles;
using CLARIHR.Infrastructure.Preferences;
using CLARIHR.Infrastructure.PositionDescriptionCatalogs;
using CLARIHR.Infrastructure.PositionSlots;
using CLARIHR.Infrastructure.Policies;
using CLARIHR.Infrastructure.Persistence;
using CLARIHR.Infrastructure.Platform;
using CLARIHR.Infrastructure.Reports;
using CLARIHR.Infrastructure.Reports.Documents;
using CLARIHR.Infrastructure.SalaryTabulator;
using CLARIHR.Infrastructure.SystemCatalogs;
using CLARIHR.Infrastructure.Tenancy;
using CLARIHR.Infrastructure.Time;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace CLARIHR.Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;

        services.Configure<DatabaseOptions>(configuration.GetSection(DatabaseOptions.SectionName));
        services.Configure<JwtTokenOptions>(configuration.GetSection(JwtTokenOptions.SectionName));
        services.Configure<PasswordResetOptions>(configuration.GetSection(PasswordResetOptions.SectionName));
        services.Configure<GoogleAuthOptions>(configuration.GetSection(GoogleAuthOptions.SectionName));
        services.Configure<FileStorageOptions>(configuration.GetSection(FileStorageOptions.SectionName));
        services.Configure<ReportPerformanceOptions>(configuration.GetSection(ReportPerformanceOptions.SectionName));
        services.Configure<FieldPermissionCacheOptions>(configuration.GetSection(FieldPermissionCacheOptions.SectionName));
        services.Configure<CompanyOwnershipOptions>(configuration.GetSection(CompanyOwnershipOptions.SectionName));
        services.Configure<CompanySubscriptionLifecycleOptions>(configuration.GetSection(CompanySubscriptionLifecycleOptions.SectionName));
        services.AddHttpContextAccessor();

        services.AddSingleton<IDateTimeProvider, SystemDateTimeProvider>();
        services.AddSingleton<BlobServiceClientFactory>();
        services.AddSingleton<IPasswordHasher, BuiltInPasswordHasher>();
        services.AddMemoryCache();
        services.AddSingleton<RefreshTokenHasher>();
        services.AddSingleton<IRefreshTokenHasher>(serviceProvider => serviceProvider.GetRequiredService<RefreshTokenHasher>());
        services.AddSingleton<IInvitationTokenHasher>(serviceProvider => serviceProvider.GetRequiredService<RefreshTokenHasher>());
        services.AddSingleton<IPasswordResetTokenHasher>(serviceProvider => serviceProvider.GetRequiredService<RefreshTokenHasher>());
        services.AddSingleton<IPasswordResetTokenGenerator, PasswordResetTokenGenerator>();
        services.AddSingleton<IGoogleIdTokenValidator, GoogleIdTokenValidator>();
        services.AddSingleton<AmbientTenantContext>();
        services.AddScoped<ITenantContext, HttpTenantContext>();
        services.AddScoped<ICurrentUserService, HttpCurrentUserService>();
        services.AddScoped<IAuditLogRepository, AuditLogRepository>();
        services.AddScoped<IAuditService, AuditService>();
        services.AddScoped<IPlatformAuditService, PlatformAuditService>();
        services.AddSingleton<IAuditSanitizer, AuditSanitizer>();
        services.AddSingleton<IBackendMessageLocalizer, ResourceBackendMessageLocalizer>();
        services.AddScoped<ICompanyRepository, CompanyRepository>();
        services.AddScoped<ICommercialAddonRepository, CommercialAddonRepository>();
        services.AddScoped<ICommercialPlanRepository, CommercialPlanRepository>();
        services.AddScoped<ICompanySubscriptionRepository, CompanySubscriptionRepository>();
        services.AddScoped<CompanySubscriptionLifecycleProcessor>();
        services.AddScoped<IUserCompanyRepository, UserCompanyRepository>();
        services.AddScoped<ICompanyOwnershipPolicy, CompanyOwnershipPolicy>();
        services.AddScoped<IInvitationTokenRepository, InvitationTokenRepository>();
        services.AddScoped<IEmailService, LoggingEmailService>();
        services.AddScoped<IPasswordResetTokenRepository, PasswordResetTokenRepository>();
        services.AddScoped<IAuthEmailService, LoggingAuthEmailService>();
        services.AddScoped<IPasswordResetLinkBuilder, PasswordResetLinkBuilder>();
        services.AddScoped<IPasswordResetPolicyProvider, PasswordResetPolicyProvider>();
        services.AddScoped<ICompanyUserAuthorizationService, CompanyUserAuthorizationService>();
        services.AddScoped<IPlanEntitlementService, PlanEntitlementService>();
        services.AddScoped<IPlatformOperatorRepository, PlatformOperatorRepository>();
        services.AddScoped<IPlatformAuthorizationService, PlatformAuthorizationService>();
        services.AddScoped<ICountryCatalogRepository, CountryCatalogRepository>();
        services.AddScoped<IBankCatalogRepository, BankCatalogRepository>();
        services.AddScoped<ISystemCatalogRepository, SystemCatalogRepository>();
        services.AddScoped<IInternalCatalogRepository, InternalCatalogRepository>();
        services.AddScoped<ILocationHierarchyRepository, LocationHierarchyRepository>();
        services.AddScoped<ILocationGroupRepository, LocationGroupRepository>();
        services.AddScoped<IWorkCenterTypeRepository, WorkCenterTypeRepository>();
        services.AddScoped<IWorkCenterRepository, WorkCenterRepository>();
        services.AddScoped<ILocationDependencyPolicy, LocationDependencyPolicy>();
        services.AddScoped<ILocationSeedService, LocationSeedService>();
        services.AddScoped<ILocationAuthorizationService, LocationAuthorizationService>();
        services.AddScoped<IOrgUnitRepository, OrgUnitRepository>();
        services.AddScoped<IOrgUnitAuthorizationService, OrgUnitAuthorizationService>();
        services.AddScoped<IOrgStructureCatalogRepository, OrgStructureCatalogRepository>();
        services.AddScoped<IOrgStructureCatalogAuthorizationService, OrgStructureCatalogAuthorizationService>();
        services.AddScoped<IOrgStructureCatalogSeedService, OrgStructureCatalogSeedService>();
        services.AddScoped<IJobProfileRepository, JobProfileRepository>();
        services.AddScoped<IJobCatalogRepository, JobCatalogRepository>();
        services.AddScoped<IJobProfileCompensationRepository, JobProfileCompensationRepository>();
        services.AddScoped<IJobProfileAuthorizationService, JobProfileAuthorizationService>();
        services.AddScoped<IPositionDescriptionCatalogRepository, PositionDescriptionCatalogRepository>();
        services.AddScoped<IPositionDescriptionCatalogAuthorizationService, PositionDescriptionCatalogAuthorizationService>();
        services.AddScoped<PositionDescriptionCatalogSeedService>();
        services.AddScoped<IPositionSlotRepository, PositionSlotRepository>();
        services.AddScoped<IPositionSlotAuthorizationService, PositionSlotAuthorizationService>();
        services.AddScoped<ICostCenterRepository, CostCenterRepository>();
        services.AddScoped<ICostCenterAuthorizationService, CostCenterAuthorizationService>();
        services.AddScoped<ICompetencyFrameworkRepository, CompetencyFrameworkRepository>();
        services.AddScoped<ICompetencyFrameworkAuthorizationService, CompetencyFrameworkAuthorizationService>();
        services.AddScoped<ILegalRepresentativeRepository, LegalRepresentativeRepository>();
        services.AddScoped<ILegalRepresentativeAuthorizationService, LegalRepresentativeAuthorizationService>();
        services.AddScoped<LegalRepresentativePositionTitleCatalogSeedService>();
        services.AddScoped<LegalRepresentativeRepresentationTypeCatalogSeedService>();
        services.AddScoped<IPersonnelFileRepository, PersonnelFileRepository>();
        services.AddScoped<IEducationCatalogRepository, EducationCatalogRepository>();
        services.AddScoped<IDocumentTypeCatalogRepository, DocumentTypeCatalogs.DocumentTypeCatalogRepository>();
        services.AddScoped<IPersonnelFileProfilePhotoService, PersonnelFileProfilePhotoService>();
        services.AddScoped<IPersonnelFileEmployeeRepository, PersonnelFileEmployeeRepository>();
        services.AddScoped<IPersonnelFileAuthorizationService, PersonnelFileAuthorizationService>();
        services.AddScoped<ISalaryTabulatorRepository, SalaryTabulatorRepository>();
        services.AddScoped<ISalaryTabulatorAuthorizationService, SalaryTabulatorAuthorizationService>();
        services.AddSingleton<IReportCapabilityRegistry, ReportCapabilityRegistry>();
        services.AddScoped<IReportExportJobRepository, ReportExportJobRepository>();
        services.AddScoped<IReportExportJobGenerator, ReportExportJobGenerator>();
        services.AddScoped<IReportExportJobProcessor, ReportExportJobProcessor>();
        services.AddScoped<IDocumentPdfRenderer<JobProfilePrintResponse>, JobProfilePdfRenderer>();
        services.AddScoped<IResourceActionPolicyService, ResourceActionPolicyService>();
        services.AddScoped<IUnitOfWork, UnitOfWork>();
        services.AddScoped<IExternalAuthProviderService, GoogleExternalAuthProviderService>();
        services.AddScoped<IUserRepository, UserRepository>();
        services.AddScoped<IRefreshTokenRepository, RefreshTokenRepository>();
        services.AddScoped<IUserPreferenceRepository, UserPreferenceRepository>();
        services.AddScoped<ICompanyPreferenceRepository, CompanyPreferenceRepository>();
        services.AddScoped<ICompanyPreferenceAuthorizationService, CompanyPreferenceAuthorizationService>();
        services.AddScoped<ITokenService, JwtTokenService>();
        services.AddScoped<IRbacAuthorizationService, RbacAuthorizationService>();
        services.AddScoped<IIamAdministrationRepository, IamAdministrationRepository>();
        services.AddScoped<IIamAdministrationAuthorizationService, IamAdministrationAuthorizationService>();
        services.AddScoped<DevSeedService>();
        services.AddSingleton<IFieldPermissionOverrideCache, FieldPermissionOverrideCache>();
        services.AddScoped<IFieldAccessProfileService, FieldAccessProfileService>();
        services.AddScoped<IFieldPermissionService, FieldPermissionService>();
        services.AddSingleton<IFieldSerializationService, FieldSerializationService>();
        services.AddScoped<IFileRepository, FileRepository>();
        services.AddScoped<IFileStorageProvider, AzureBlobStorageProvider>();
        services.AddScoped<IFileStorageProviderResolver, CompositeFileStorageProviderResolver>();
        services.AddSingleton<IFilePurposeRuleProvider, FilePurposeRuleProvider>();
        services.AddSingleton<IFileObjectKeyBuilder, FileObjectKeyBuilder>();
        services.AddHostedService<CompanySubscriptionLifecycleBackgroundService>();
        services.AddHostedService<ReportExportJobBackgroundService>();
        services.AddHostedService<PendingFileCleanupBackgroundService>();

        services.AddDbContext<ApplicationDbContext>((serviceProvider, optionsBuilder) =>
        {
            var databaseOptions = serviceProvider.GetRequiredService<IOptions<DatabaseOptions>>().Value;

            optionsBuilder.EnableDetailedErrors();
            optionsBuilder.EnableSensitiveDataLogging(false);

            PostgreSqlOptionsConfigurator.Configure(optionsBuilder, databaseOptions.ConnectionString);
        });

        services.AddScoped<IApplicationDbContext>(serviceProvider => serviceProvider.GetRequiredService<ApplicationDbContext>());

        return services;
    }
}
