using CLARIHR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CLARIHR.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513001000_AddJobProfileCompensationsTable")]
    public partial class AddJobProfileCompensationsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS job_profile_compensations (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    public_id uuid NOT NULL,
                    tenant_id uuid NOT NULL,
                    job_profile_id bigint NOT NULL,
                    salary_tabulator_line_id bigint NOT NULL,
                    notes character varying(1000),
                    concurrency_token uuid NOT NULL,
                    created_utc timestamp with time zone NOT NULL DEFAULT now(),
                    modified_utc timestamp with time zone,
                    CONSTRAINT pk_job_profile_compensations PRIMARY KEY (id),
                    CONSTRAINT uq_job_profile_compensations__public_id UNIQUE (public_id),
                    CONSTRAINT uq_job_profile_compensations__job_profile_id UNIQUE (job_profile_id),
                    CONSTRAINT fk_job_profile_compensations__job_profile FOREIGN KEY (job_profile_id)
                        REFERENCES job_profiles (id) ON DELETE CASCADE,
                    CONSTRAINT fk_job_profile_compensations__salary_tabulator_line FOREIGN KEY (salary_tabulator_line_id)
                        REFERENCES salary_tabulator_lines (id) ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS ix_job_profile_compensations__salary_tabulator_line
                    ON job_profile_compensations (salary_tabulator_line_id);
                """);

            migrationBuilder.Sql(
                """
                -- Best-effort backfill: resolves a single salary_tabulator_line per profile based on legacy codes
                -- and the profile's effective date. Profiles without a unique match are skipped silently.
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'job_profiles'
                          AND column_name = 'normalized_salary_scale_code'
                    ) THEN
                        INSERT INTO job_profile_compensations
                            (public_id, tenant_id, job_profile_id, salary_tabulator_line_id, notes, concurrency_token, created_utc)
                        SELECT
                            gen_random_uuid(),
                            jp.tenant_id,
                            jp.id,
                            matched.line_id,
                            NULL,
                            (md5(random()::text || clock_timestamp()::text))::uuid,
                            now()
                        FROM job_profiles jp
                        JOIN LATERAL (
                            SELECT stl.id AS line_id
                            FROM salary_tabulator_lines stl
                            JOIN job_catalog_items jci_class ON jci_class.id = jp.salary_class_catalog_item_id
                            WHERE stl.tenant_id = jp.tenant_id
                              AND stl.normalized_salary_scale_code = jp.normalized_salary_scale_code
                              AND stl.normalized_salary_class_code = jci_class.normalized_code
                              AND stl.is_active = true
                              AND stl.effective_from_utc <= COALESCE(jp.effective_to_utc, 'infinity'::timestamptz)
                              AND (stl.effective_to_utc IS NULL OR stl.effective_to_utc >= COALESCE(jp.effective_from_utc, now()))
                            ORDER BY stl.effective_from_utc DESC
                            LIMIT 1
                        ) AS matched ON TRUE
                        WHERE jp.salary_class_catalog_item_id IS NOT NULL
                          AND jp.normalized_salary_scale_code IS NOT NULL
                          AND NOT EXISTS (
                              SELECT 1 FROM job_profile_compensations existing
                              WHERE existing.job_profile_id = jp.id
                          );
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE job_profiles DROP CONSTRAINT IF EXISTS fk_job_profiles__salary_class_catalog_item;
                DROP INDEX IF EXISTS ix_job_profiles__tenant_salary_class;
                DROP INDEX IF EXISTS ix_job_profiles__tenant_salary_scale;
                DROP INDEX IF EXISTS "IX_job_profiles_SalaryClassCatalogItemId";
                DROP INDEX IF EXISTS ix_job_profiles_salaryclasscatalogitemid;

                ALTER TABLE job_profiles DROP COLUMN IF EXISTS salary_class_catalog_item_id;
                ALTER TABLE job_profiles DROP COLUMN IF EXISTS salary_scale_code;
                ALTER TABLE job_profiles DROP COLUMN IF EXISTS normalized_salary_scale_code;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE job_profiles ADD COLUMN IF NOT EXISTS salary_class_catalog_item_id bigint;
                ALTER TABLE job_profiles ADD COLUMN IF NOT EXISTS salary_scale_code character varying(50);
                ALTER TABLE job_profiles ADD COLUMN IF NOT EXISTS normalized_salary_scale_code character varying(50);

                DROP TABLE IF EXISTS job_profile_compensations;
                """);
        }
    }
}
