using CLARIHR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CLARIHR.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513001000_AddJobProfileCompensationsTable")]
    public partial class AddJobProfileCompensationsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS job_profile_compensations (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    public_id uuid NOT NULL,
                    tenant_id uuid NOT NULL,
                    job_profile_id bigint NOT NULL,
                    salary_tabulator_line_id bigint NOT NULL,
                    notes character varying(1000),
                    concurrency_token uuid NOT NULL,
                    created_utc timestamp with time zone NOT NULL DEFAULT now(),
                    modified_utc timestamp with time zone,
                    CONSTRAINT pk_job_profile_compensations PRIMARY KEY (id),
                    CONSTRAINT uq_job_profile_compensations__public_id UNIQUE (public_id),
                    CONSTRAINT uq_job_profile_compensations__job_profile_id UNIQUE (job_profile_id),
                    CONSTRAINT fk_job_profile_compensations__job_profile FOREIGN KEY (job_profile_id)
                        REFERENCES job_profiles (id) ON DELETE CASCADE,
                    CONSTRAINT fk_job_profile_compensations__salary_tabulator_line FOREIGN KEY (salary_tabulator_line_id)
                        REFERENCES salary_tabulator_lines (id) ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS ix_job_profile_compensations__salary_tabulator_line
                    ON job_profile_compensations (salary_tabulator_line_id);
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE job_profiles DROP CONSTRAINT IF EXISTS fk_job_profiles__salary_class_catalog_item;
                DROP INDEX IF EXISTS ix_job_profiles__tenant_salary_class;
                DROP INDEX IF EXISTS ix_job_profiles__tenant_salary_scale;
                DROP INDEX IF EXISTS "IX_job_profiles_SalaryClassCatalogItemId";
                DROP INDEX IF EXISTS ix_job_profiles_salaryclasscatalogitemid;

                ALTER TABLE job_profiles DROP COLUMN IF EXISTS salary_class_catalog_item_id;
                ALTER TABLE job_profiles DROP COLUMN IF EXISTS salary_scale_code;
                ALTER TABLE job_profiles DROP COLUMN IF EXISTS normalized_salary_scale_code;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE job_profiles ADD COLUMN IF NOT EXISTS salary_class_catalog_item_id bigint;
                ALTER TABLE job_profiles ADD COLUMN IF NOT EXISTS salary_scale_code character varying(50);
                ALTER TABLE job_profiles ADD COLUMN IF NOT EXISTS normalized_salary_scale_code character varying(50);

                DROP TABLE IF EXISTS job_profile_compensations;
                """);
        }
    }
}
